# table

In [3]:

from prettytable import PrettyTable
table = PrettyTable()
table.field_names = ["solve null values on number data", "solve null values on category data", "repeated vvalues", "aggs for previous_table"]
table.add_row(["I choose to drop columns had null values above 58%","I drop columm above 60%", "made threshold 80%","I choose category data I will take it to join with application"])
table.add_row(["solve by using median with data under 20% null values and I used median beccause it's a skewing data", "I used SimpleImputer algorithm to solve null values by using mode","drop above 80%","I made aggs for category by using count"])
table.add_row(["the other columns I used algorithm is called MissForest and It's based on RandomForest", "concat number and category","save new data", "split values on pivot tables"])
table2 = PrettyTable()
table2.field_names=["aggs","join"]
table2.add_row(["use mean aggregiation for some columns","left join with main table"])
table2.add_row(["use max aggregiation for some columns","left join with main table"])
table2.add_row(["use count aggregiation for some columns","left join with main table"])
table3 = PrettyTable()
table3.field_names=["didvde by 360","get outlieres","count of resolving by null value"]
table3.add_row(["DAYS_ID_PUBLISH_Years","no outliers","None"])
table3.add_row(["DAYS_BIRTH_YEARS","no outliers","None"])
table3.add_row(["DAYS_REGISTRATION_Year","outliers","659"])
table3.add_row(["DAYS_EMPLOYED_Years","outliees","72217"])

# approche

In [5]:
print(table)
print(table2)
print(table3)

+------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------+--------------------+----------------------------------------------------------------+
|                                   solve null values on number data                                   |                 solve null values on category data                |  repeated vvalues  |                    aggs for previous_table                     |
+------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------+--------------------+----------------------------------------------------------------+
|                          I choose to drop columns had null values above 58%                          |                      I drop columm above 60%                      | made threshold 80% | I choose category data I will take it to join with application |
| solve by using median with data under 20% null values and I used median beccause it's a skewing data | I used SimpleImputer algorithm to solve null values by using mode |   drop above 80%   |            I made aggs for category by using count             |
|        the other columns I used algorithm is called MissForest and It's based on RandomForest        |                     concat number and category                    |   save new data    |                  split values on pivot tables                  |
+------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------+--------------------+----------------------------------------------------------------+
+-----------------------------------------+---------------------------+
|                   aggs                  |            join           |
+-----------------------------------------+---------------------------+
|  use mean aggregiation for some columns | left join with main table |
|  use max aggregiation for some columns  | left join with main table |
| use count aggregiation for some columns | left join with main table |
+-----------------------------------------+---------------------------+
+------------------------+---------------+----------------------------------+
|     didvde by 360      | get outlieres | count of resolving by null value |
+------------------------+---------------+----------------------------------+
| DAYS_ID_PUBLISH_Years  |  no outliers  |               None               |
|    DAYS_BIRTH_YEARS    |  no outliers  |               None               |
| DAYS_REGISTRATION_Year |    outliers   |               659                |
|  DAYS_EMPLOYED_Years   |    outliees   |              72217               |
+------------------------+---------------+----------------------------------+

# imports

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
from missforest import MissForest

pd.set_option('display.width', None)
import polars as pl

c:\Users\youss\AppData\Local\Programs\Python\Python312\Lib\site-packages\dask\dataframe\__init__.py:49: FutureWarning:
Dask dataframe query planning is disabled because dask-expr is not installed.

You can install it with `pip install dask[dataframe]` or `conda install dask`.
This will raise in a future version.

  warnings.warn(msg, FutureWarning)

# showing main table

In [4]:
app_data=pl.read_csv("datasets/application_train.csv")
app_data.head()

shape: (5, 122)
┌────────────┬────────┬────────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ SK_ID_CURR ┆ TARGET ┆ NAME_CONTR ┆ CODE_GEND ┆ … ┆ AMT_REQ_C ┆ AMT_REQ_C ┆ AMT_REQ_C ┆ AMT_REQ_C │
│ ---        ┆ ---    ┆ ACT_TYPE   ┆ ER        ┆   ┆ REDIT_BUR ┆ REDIT_BUR ┆ REDIT_BUR ┆ REDIT_BUR │
│ i64        ┆ i64    ┆ ---        ┆ ---       ┆   ┆ EAU_WEEK  ┆ EAU_MON   ┆ EAU_QRT   ┆ EAU_YEAR  │
│            ┆        ┆ str        ┆ str       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆        ┆            ┆           ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞════════════╪════════╪════════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 100002     ┆ 1      ┆ Cash loans ┆ M         ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 1.0       │
│ 100003     ┆ 0      ┆ Cash loans ┆ F         ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0       │
│ 100004     ┆ 0      ┆ Revolving  ┆ M         ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0       │
│            ┆        ┆ loans      ┆           ┆   ┆           ┆           ┆           ┆           │
│ 100006     ┆ 0      ┆ Cash loans ┆ F         ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 100007     ┆ 0      ┆ Cash loans ┆ M         ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0       │
└────────────┴────────┴────────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [5]:
app_data.is_duplicated().sum()

0

In [6]:
app_data.null_count().sum()

shape: (1, 122)
┌────────────┬────────┬────────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ SK_ID_CURR ┆ TARGET ┆ NAME_CONTR ┆ CODE_GEND ┆ … ┆ AMT_REQ_C ┆ AMT_REQ_C ┆ AMT_REQ_C ┆ AMT_REQ_C │
│ ---        ┆ ---    ┆ ACT_TYPE   ┆ ER        ┆   ┆ REDIT_BUR ┆ REDIT_BUR ┆ REDIT_BUR ┆ REDIT_BUR │
│ u32        ┆ u32    ┆ ---        ┆ ---       ┆   ┆ EAU_WEEK  ┆ EAU_MON   ┆ EAU_QRT   ┆ EAU_YEAR  │
│            ┆        ┆ u32        ┆ u32       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆        ┆            ┆           ┆   ┆ u32       ┆ u32       ┆ u32       ┆ u32       │
╞════════════╪════════╪════════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 0          ┆ 0      ┆ 0          ┆ 0         ┆ … ┆ 41519     ┆ 41519     ┆ 41519     ┆ 41519     │
└────────────┴────────┴────────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

# Reprocessing main table

In [7]:
int_data = app_data.select([pl.col(c).cast(pl.Int64) for c in app_data.columns if app_data[c].dtype == pl.Int64])

df_float = app_data.select([pl.col(c).cast(pl.Float64) for c in app_data.columns if app_data[c].dtype == pl.Float64])

cat_data = app_data.select([pl.col(c).cast(pl.Utf8) for c in app_data.columns if app_data[c].dtype == pl.Utf8])

In [8]:
number_data = pl.concat([int_data, df_float], how="horizontal")

In [9]:
number_data.head()

shape: (5, 106)
┌────────────┬────────┬────────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ SK_ID_CURR ┆ TARGET ┆ CNT_CHILDR ┆ DAYS_BIRT ┆ … ┆ AMT_REQ_C ┆ AMT_REQ_C ┆ AMT_REQ_C ┆ AMT_REQ_C │
│ ---        ┆ ---    ┆ EN         ┆ H         ┆   ┆ REDIT_BUR ┆ REDIT_BUR ┆ REDIT_BUR ┆ REDIT_BUR │
│ i64        ┆ i64    ┆ ---        ┆ ---       ┆   ┆ EAU_WEEK  ┆ EAU_MON   ┆ EAU_QRT   ┆ EAU_YEAR  │
│            ┆        ┆ i64        ┆ i64       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆        ┆            ┆           ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞════════════╪════════╪════════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 100002     ┆ 1      ┆ 0          ┆ -9461     ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 1.0       │
│ 100003     ┆ 0      ┆ 0          ┆ -16765    ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0       │
│ 100004     ┆ 0      ┆ 0          ┆ -19046    ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0       │
│ 100006     ┆ 0      ┆ 0          ┆ -19005    ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 100007     ┆ 0      ┆ 0          ┆ -19932    ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0       │
└────────────┴────────┴────────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

# solve null values on number

In [10]:
total_rows = number_data.height

null_counts = number_data.null_count()

nulls_df_numbers = pl.DataFrame({
    "Column_Name": null_counts.columns,
    "Nulls_Count": null_counts.to_pandas().values.flatten()
})

nulls_df_numbers = nulls_df_numbers.with_columns(
    (pl.col("Nulls_Count") / total_rows * 100).alias("Percentage")
)

nulls_df_numbers = nulls_df_numbers.sort("Nulls_Count", descending=True)

nulls_df_numbers = nulls_df_numbers.filter(pl.col("Nulls_Count") > 0)

In [11]:
nulls_df_numbers

shape: (61, 3)
┌──────────────────────────┬─────────────┬────────────┐
│ Column_Name              ┆ Nulls_Count ┆ Percentage │
│ ---                      ┆ ---         ┆ ---        │
│ str                      ┆ u32         ┆ f64        │
╞══════════════════════════╪═════════════╪════════════╡
│ COMMONAREA_AVG           ┆ 214865      ┆ 69.872297  │
│ COMMONAREA_MODE          ┆ 214865      ┆ 69.872297  │
│ COMMONAREA_MEDI          ┆ 214865      ┆ 69.872297  │
│ NONLIVINGAPARTMENTS_AVG  ┆ 213514      ┆ 69.432963  │
│ NONLIVINGAPARTMENTS_MODE ┆ 213514      ┆ 69.432963  │
│ …                        ┆ …           ┆ …          │
│ EXT_SOURCE_2             ┆ 660         ┆ 0.214626   │
│ AMT_GOODS_PRICE          ┆ 278         ┆ 0.090403   │
│ AMT_ANNUITY              ┆ 12          ┆ 0.003902   │
│ CNT_FAM_MEMBERS          ┆ 2           ┆ 0.00065    │
│ DAYS_LAST_PHONE_CHANGE   ┆ 1           ┆ 0.000325   │
└──────────────────────────┴─────────────┴────────────┘

In [12]:
for col, percentage in zip(nulls_df_numbers['Column_Name'], nulls_df_numbers['Percentage']):
    if percentage <= 20:
        median_value = number_data.select(pl.col(col).median()).to_numpy()[0][0]  
        number_data = number_data.with_columns(
            pl.col(col).fill_null(median_value).alias(col)
        )
    elif percentage > 58:
        number_data = number_data.drop(col)

number_data_cleaned = number_data
number_data_cleaned

shape: (307_511, 84)
┌────────────┬────────┬────────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ SK_ID_CURR ┆ TARGET ┆ CNT_CHILDR ┆ DAYS_BIRT ┆ … ┆ AMT_REQ_C ┆ AMT_REQ_C ┆ AMT_REQ_C ┆ AMT_REQ_C │
│ ---        ┆ ---    ┆ EN         ┆ H         ┆   ┆ REDIT_BUR ┆ REDIT_BUR ┆ REDIT_BUR ┆ REDIT_BUR │
│ i64        ┆ i64    ┆ ---        ┆ ---       ┆   ┆ EAU_WEEK  ┆ EAU_MON   ┆ EAU_QRT   ┆ EAU_YEAR  │
│            ┆        ┆ i64        ┆ i64       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆        ┆            ┆           ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞════════════╪════════╪════════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 100002     ┆ 1      ┆ 0          ┆ -9461     ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 1.0       │
│ 100003     ┆ 0      ┆ 0          ┆ -16765    ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0       │
│ 100004     ┆ 0      ┆ 0          ┆ -19046    ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0       │
│ 100006     ┆ 0      ┆ 0          ┆ -19005    ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 1.0       │
│ 100007     ┆ 0      ┆ 0          ┆ -19932    ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0       │
│ …          ┆ …      ┆ …          ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 456251     ┆ 0      ┆ 0          ┆ -9327     ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 1.0       │
│ 456252     ┆ 0      ┆ 0          ┆ -20775    ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 1.0       │
│ 456253     ┆ 0      ┆ 0          ┆ -14966    ┆ … ┆ 0.0       ┆ 1.0       ┆ 0.0       ┆ 1.0       │
│ 456254     ┆ 1      ┆ 0          ┆ -11961    ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0       │
│ 456255     ┆ 0      ┆ 0          ┆ -16856    ┆ … ┆ 0.0       ┆ 2.0       ┆ 0.0       ┆ 1.0       │
└────────────┴────────┴────────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [13]:
total_rows = number_data_cleaned.height

null_counts = number_data_cleaned.null_count()

nulls_df_numbers = pl.DataFrame({
    "Column_Name": null_counts.columns,
    "Nulls_Count": null_counts.to_pandas().values.flatten()
})

nulls_df_numbers = nulls_df_numbers.with_columns(
    (pl.col("Nulls_Count") / total_rows * 100).alias("Percentage")
)

nulls_df_numbers = nulls_df_numbers.sort("Nulls_Count", descending=True)

nulls_df_numbers = nulls_df_numbers.filter(pl.col("Nulls_Count") > 0)

In [14]:
nulls_df_numbers

shape: (23, 3)
┌──────────────────────────────┬─────────────┬────────────┐
│ Column_Name                  ┆ Nulls_Count ┆ Percentage │
│ ---                          ┆ ---         ┆ ---        │
│ str                          ┆ u32         ┆ f64        │
╞══════════════════════════════╪═════════════╪════════════╡
│ EXT_SOURCE_1                 ┆ 173378      ┆ 56.381073  │
│ NONLIVINGAREA_AVG            ┆ 169682      ┆ 55.179164  │
│ NONLIVINGAREA_MODE           ┆ 169682      ┆ 55.179164  │
│ NONLIVINGAREA_MEDI           ┆ 169682      ┆ 55.179164  │
│ ELEVATORS_AVG                ┆ 163891      ┆ 53.29598   │
│ …                            ┆ …           ┆ …          │
│ FLOORSMAX_MEDI               ┆ 153020      ┆ 49.760822  │
│ YEARS_BEGINEXPLUATATION_AVG  ┆ 150007      ┆ 48.781019  │
│ YEARS_BEGINEXPLUATATION_MODE ┆ 150007      ┆ 48.781019  │
│ YEARS_BEGINEXPLUATATION_MEDI ┆ 150007      ┆ 48.781019  │
│ TOTALAREA_MODE               ┆ 148431      ┆ 48.268517  │
└──────────────────────────────┴─────────────┴────────────┘

In [15]:
number_data_pandas = number_data_cleaned.to_pandas()

mf = MissForest()
mf.fit(number_data_pandas)

train_imputed = mf.transform(number_data_pandas)

train_imputed_polars = pl.from_pandas(train_imputed)

c:\Users\youss\AppData\Local\Programs\Python\Python312\Lib\site-packages\missforest\missforest.py:318: UserWarning: Label encoding is no longer performed by default. Users will have to perform categorical features encoding by themselves.
  warnings.warn("Label encoding is no longer performed by default. "
100%|██████████| 5/5 [12:40<00:00, 152.19s/it]
c:\Users\youss\AppData\Local\Programs\Python\Python312\Lib\site-packages\missforest\missforest.py:462: UserWarning: Label encoding is no longer performed by default. Users will have to perform categorical features encoding by themselves.
  warnings.warn("Label encoding is no longer performed by default. "
c:\Users\youss\AppData\Local\Programs\Python\Python312\Lib\site-packages\missforest\missforest.py:466: UserWarning: In version 4.0.0, estimator fitting process is moved to `fit` method. `MissForest` will now imputes unseen missing values with fitted estimators with `transform` method. To retain the old behaviour, use `fit_transform` to fit the whole unseen data instead.
  warnings.warn(f"In version {VERSION}, estimator fitting process is "
 40%|████      | 2/5 [00:14<00:21,  7.29s/it]c:\Users\youss\AppData\Local\Programs\Python\Python312\Lib\site-packages\missforest\missforest.py:288: UserWarning: NRMSE increased.
  warnings.warn("NRMSE increased.")
c:\Users\youss\AppData\Local\Programs\Python\Python312\Lib\site-packages\missforest\missforest.py:528: UserWarning: Stopping criterion triggered during transform. Before last imputation matrix will be returned.
  warnings.warn(
 40%|████      | 2/5 [00:21<00:32, 10.98s/it]

In [16]:
number_data_imputed = pd.DataFrame(train_imputed_polars, columns=number_data.columns, index=number_data_pandas.index)

print(number_data_imputed.isnull().sum())

SK_ID_CURR                      0
TARGET                          0
CNT_CHILDREN                    0
DAYS_BIRTH                      0
DAYS_EMPLOYED                   0
DAYS_ID_PUBLISH                 0
FLAG_MOBIL                      0
FLAG_EMP_PHONE                  0
FLAG_WORK_PHONE                 0
FLAG_CONT_MOBILE                0
FLAG_PHONE                      0
FLAG_EMAIL                      0
REGION_RATING_CLIENT            0
REGION_RATING_CLIENT_W_CITY     0
HOUR_APPR_PROCESS_START         0
REG_REGION_NOT_LIVE_REGION      0
REG_REGION_NOT_WORK_REGION      0
LIVE_REGION_NOT_WORK_REGION     0
REG_CITY_NOT_LIVE_CITY          0
REG_CITY_NOT_WORK_CITY          0
LIVE_CITY_NOT_WORK_CITY         0
FLAG_DOCUMENT_2                 0
FLAG_DOCUMENT_3                 0
FLAG_DOCUMENT_4                 0
FLAG_DOCUMENT_5                 0
FLAG_DOCUMENT_6                 0
FLAG_DOCUMENT_7                 0
FLAG_DOCUMENT_8                 0
FLAG_DOCUMENT_9                 0
FLAG_DOCUMENT_10                0
FLAG_DOCUMENT_11                0
FLAG_DOCUMENT_12                0
FLAG_DOCUMENT_13                0
FLAG_DOCUMENT_14                0
FLAG_DOCUMENT_15                0
FLAG_DOCUMENT_16                0
FLAG_DOCUMENT_17                0
FLAG_DOCUMENT_18                0
FLAG_DOCUMENT_19                0
FLAG_DOCUMENT_20                0
FLAG_DOCUMENT_21                0
AMT_INCOME_TOTAL                0
AMT_CREDIT                      0
AMT_ANNUITY                     0
AMT_GOODS_PRICE                 0
REGION_POPULATION_RELATIVE      0
DAYS_REGISTRATION               0
CNT_FAM_MEMBERS                 0
EXT_SOURCE_1                    0
EXT_SOURCE_2                    0
EXT_SOURCE_3                    0
APARTMENTS_AVG                  0
YEARS_BEGINEXPLUATATION_AVG     0
ELEVATORS_AVG                   0
ENTRANCES_AVG                   0
FLOORSMAX_AVG                   0
LIVINGAREA_AVG                  0
NONLIVINGAREA_AVG               0
APARTMENTS_MODE                 0
YEARS_BEGINEXPLUATATION_MODE    0
ELEVATORS_MODE                  0
ENTRANCES_MODE                  0
FLOORSMAX_MODE                  0
LIVINGAREA_MODE                 0
NONLIVINGAREA_MODE              0
APARTMENTS_MEDI                 0
YEARS_BEGINEXPLUATATION_MEDI    0
ELEVATORS_MEDI                  0
ENTRANCES_MEDI                  0
FLOORSMAX_MEDI                  0
LIVINGAREA_MEDI                 0
NONLIVINGAREA_MEDI              0
TOTALAREA_MODE                  0
OBS_30_CNT_SOCIAL_CIRCLE        0
DEF_30_CNT_SOCIAL_CIRCLE        0
OBS_60_CNT_SOCIAL_CIRCLE        0
DEF_60_CNT_SOCIAL_CIRCLE        0
DAYS_LAST_PHONE_CHANGE          0
AMT_REQ_CREDIT_BUREAU_HOUR      0
AMT_REQ_CREDIT_BUREAU_DAY       0
AMT_REQ_CREDIT_BUREAU_WEEK      0
AMT_REQ_CREDIT_BUREAU_MON       0
AMT_REQ_CREDIT_BUREAU_QRT       0
AMT_REQ_CREDIT_BUREAU_YEAR      0
dtype: int64

# solve null values on object

In [17]:
total_rows = cat_data.height

null_counts = cat_data.null_count()

nulls_df_cat = pl.DataFrame({
    "Column_Name": null_counts.columns,
    "Nulls_Count": null_counts.to_pandas().values.flatten()
})

nulls_df_cat = nulls_df_cat.with_columns(
    (pl.col("Nulls_Count") / total_rows * 100).alias("Percentage")
)

nulls_df_cat = nulls_df_cat.sort("Nulls_Count", descending=True)

nulls_df_cat = nulls_df_cat.filter(pl.col("Nulls_Count") > 0)

In [18]:
nulls_df_cat

shape: (6, 3)
┌─────────────────────┬─────────────┬────────────┐
│ Column_Name         ┆ Nulls_Count ┆ Percentage │
│ ---                 ┆ ---         ┆ ---        │
│ str                 ┆ u32         ┆ f64        │
╞═════════════════════╪═════════════╪════════════╡
│ FONDKAPREMONT_MODE  ┆ 210295      ┆ 68.386172  │
│ WALLSMATERIAL_MODE  ┆ 156341      ┆ 50.840783  │
│ HOUSETYPE_MODE      ┆ 154297      ┆ 50.176091  │
│ EMERGENCYSTATE_MODE ┆ 145755      ┆ 47.398304  │
│ OCCUPATION_TYPE     ┆ 96391       ┆ 31.345545  │
│ NAME_TYPE_SUITE     ┆ 1292        ┆ 0.420148   │
└─────────────────────┴─────────────┴────────────┘

In [19]:
cat_data=cat_data.drop("FONDKAPREMONT_MODE")

In [20]:
from sklearn.impute import SimpleImputer

cat_with_pandas = cat_data.to_pandas()

cat_with_pandas = cat_with_pandas.replace({None: np.nan, pd.NA: np.nan})

print(cat_with_pandas.isnull().sum())  

cat_imputer = SimpleImputer(strategy='most_frequent')
cat_data_imputed = pd.DataFrame(
    cat_imputer.fit_transform(cat_with_pandas),
    columns=cat_with_pandas.columns
)

print(cat_data_imputed.isnull().sum())

NAME_CONTRACT_TYPE                 0
CODE_GENDER                        0
FLAG_OWN_CAR                       0
FLAG_OWN_REALTY                    0
NAME_TYPE_SUITE                 1292
NAME_INCOME_TYPE                   0
NAME_EDUCATION_TYPE                0
NAME_FAMILY_STATUS                 0
NAME_HOUSING_TYPE                  0
OCCUPATION_TYPE                96391
WEEKDAY_APPR_PROCESS_START         0
ORGANIZATION_TYPE                  0
HOUSETYPE_MODE                154297
WALLSMATERIAL_MODE            156341
EMERGENCYSTATE_MODE           145755
dtype: int64
NAME_CONTRACT_TYPE            0
CODE_GENDER                   0
FLAG_OWN_CAR                  0
FLAG_OWN_REALTY               0
NAME_TYPE_SUITE               0
NAME_INCOME_TYPE              0
NAME_EDUCATION_TYPE           0
NAME_FAMILY_STATUS            0
NAME_HOUSING_TYPE             0
OCCUPATION_TYPE               0
WEEKDAY_APPR_PROCESS_START    0
ORGANIZATION_TYPE             0
HOUSETYPE_MODE                0
WALLSMATERIAL_MODE            0
EMERGENCYSTATE_MODE           0
dtype: int64

# concat numbers with object

In [21]:
new_app_data=pd.concat([number_data_imputed,cat_data_imputed],axis=1)

In [22]:
new_app_data.head()

,SK_ID_CURR,TARGET,CNT_CHILDREN,DAYS_BIRTH,DAYS_EMPLOYED,DAYS_ID_PUBLISH,FLAG_MOBIL,FLAG_EMP_PHONE,FLAG_WORK_PHONE,FLAG_CONT_MOBILE,FLAG_PHONE,FLAG_EMAIL,REGION_RATING_CLIENT,REGION_RATING_CLIENT_W_CITY,HOUR_APPR_PROCESS_START,REG_REGION_NOT_LIVE_REGION,REG_REGION_NOT_WORK_REGION,LIVE_REGION_NOT_WORK_REGION,REG_CITY_NOT_LIVE_CITY,REG_CITY_NOT_WORK_CITY,LIVE_CITY_NOT_WORK_CITY,FLAG_DOCUMENT_2,FLAG_DOCUMENT_3,FLAG_DOCUMENT_4,FLAG_DOCUMENT_5,FLAG_DOCUMENT_6,FLAG_DOCUMENT_7,FLAG_DOCUMENT_8,FLAG_DOCUMENT_9,FLAG_DOCUMENT_10,FLAG_DOCUMENT_11,FLAG_DOCUMENT_12,FLAG_DOCUMENT_13,FLAG_DOCUMENT_14,FLAG_DOCUMENT_15,FLAG_DOCUMENT_16,FLAG_DOCUMENT_17,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,REGION_POPULATION_RELATIVE,DAYS_REGISTRATION,CNT_FAM_MEMBERS,EXT_SOURCE_1,EXT_SOURCE_2,EXT_SOURCE_3,APARTMENTS_AVG,YEARS_BEGINEXPLUATATION_AVG,ELEVATORS_AVG,ENTRANCES_AVG,FLOORSMAX_AVG,LIVINGAREA_AVG,NONLIVINGAREA_AVG,APARTMENTS_MODE,YEARS_BEGINEXPLUATATION_MODE,ELEVATORS_MODE,ENTRANCES_MODE,FLOORSMAX_MODE,LIVINGAREA_MODE,NONLIVINGAREA_MODE,APARTMENTS_MEDI,YEARS_BEGINEXPLUATATION_MEDI,ELEVATORS_MEDI,ENTRANCES_MEDI,FLOORSMAX_MEDI,LIVINGAREA_MEDI,NONLIVINGAREA_MEDI,TOTALAREA_MODE,OBS_30_CNT_SOCIAL_CIRCLE,DEF_30_CNT_SOCIAL_CIRCLE,OBS_60_CNT_SOCIAL_CIRCLE,DEF_60_CNT_SOCIAL_CIRCLE,DAYS_LAST_PHONE_CHANGE,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,NAME_TYPE_SUITE,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,NAME_HOUSING_TYPE,OCCUPATION_TYPE,WEEKDAY_APPR_PROCESS_START,ORGANIZATION_TYPE,HOUSETYPE_MODE,WALLSMATERIAL_MODE,EMERGENCYSTATE_MODE
0,100002.0,1.0,0.0,-9461.0,-637.0,-2120.0,1.0,1.0,0.0,1.0,1.0,0.0,2.0,2.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,202500.0,406597.5,24700.5,351000.0,0.018801,-3648.0,1.0,0.083037,0.262949,0.139376,0.024700,0.972200,0.000000,0.069000,0.083300,0.019000,0.000000,0.025200,0.972200,0.000000,0.069000,0.083300,0.019800,0.000000,0.025000,0.972200,0.000000,0.069000,0.083300,0.019300,0.000000,0.014900,2.0,2.0,2.0,2.0,-1134.0,0.0,0.0,0.0,0.0,0.0,1.0,Cash loans,M,N,Y,Unaccompanied,Working,Secondary / secondary special,Single / not married,House / apartment,Laborers,WEDNESDAY,Business Entity Type 3,block of flats,"Stone, brick",No
1,100003.0,0.0,0.0,-16765.0,-1188.0,-291.0,1.0,1.0,0.0,1.0,1.0,0.0,1.0,1.0,11.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,270000.0,1293502.5,35698.5,1129500.0,0.003541,-1186.0,2.0,0.311267,0.622246,0.535276,0.095900,0.985100,0.080000,0.034500,0.291700,0.054900,0.009800,0.092400,0.985100,0.080600,0.034500,0.291700,0.055400,0.000000,0.096800,0.985100,0.080000,0.034500,0.291700,0.055800,0.010000,0.071400,1.0,0.0,1.0,0.0,-828.0,0.0,0.0,0.0,0.0,0.0,0.0,Cash loans,F,N,N,Family,State servant,Higher education,Married,House / apartment,Core staff,MONDAY,School,block of flats,Block,No
2,100004.0,0.0,0.0,-19046.0,-225.0,-2531.0,1.0,1.0,1.0,1.0,1.0,0.0,2.0,2.0,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,67500.0,135000.0,6750.0,135000.0,0.010032,-4260.0,1.0,0.272586,0.555912,0.729567,0.025206,0.470849,-0.000261,0.002226,0.026318,0.121398,0.005089,-0.001742,0.217779,0.003516,0.003384,0.142304,0.127024,0.000075,0.000545,0.231712,0.002464,0.031116,0.187131,0.116373,0.000110,0.114492,0.0,0.0,0.0,0.0,-815.0,0.0,0.0,0.0,0.0,0.0,0.0,Revolving loans,M,Y,Y,Unaccompanied,Working,Secondary / secondary special,Single / not married,House / apartment,Laborers,MONDAY,Government,block of flats,Panel,No
3,100006.0,0.0,0.0,-19005.0,-3039.0,-2437.0,1.0,1.0,0.0,1.0,0.0,0.0,2.0,2.0,17.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,135000.0,312682.5,29686.5,297000.0,0.008019,-9833.0,2.0,0.309425,0.650442,0.535276,0.985202,0.494045,0.029242,0.960949,0.040093,0.267515,0.023633,0.156203,0.173594,-0.013866,0.308473,0.169275,0.337387,-0.006964,0.020599,0.254179,0.011039,0.927458,0.226234,0.282553,-0.000445,0.092209,2.0,0.0,2.0,0.0,-617.0,0.0,0.0,0.0,0.0,0.0,1.0,Cash loans,F,N,Y,Unaccompanied,Working,Secondary / secondary special,Civil marriage,House / apartment,Laborers,WEDNESDAY,Business Entity Type 3,block of flats,Panel,No
4,100007.0,0.0,0.0,-19932.0,-3038.0,-3458.0,1.0,1.0,0.0,1.0,0.0,0.0,2.0,2.0,11.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,121500.0,513000.0,21865.5,513000.0,0.028663,-4311.0,1.0,0.272085,0.322738,0.535276,0.025285,0.474059,-0.000519,-0.000514,0.029303,0.130968,0.005942,-0.001721,0.220632,0.003516,0.020376,0.157001,0.117963,0.000075,0.000545,0.239679,0.002464,0.028830,0.185531,0.102443,0.000008,0.155555,0.0,0.0,0.0,0.0,-1106.0,0.0,0.0,0.0,0.0,0.0,0.0,Cash loans,M,N,Y,Unaccompanied,Working,Secondary / secondary special,Single / not married,House / apartment,Core staff,THURSDAY,Religion,block of flats,Panel,No

In [23]:
new_app_data.isnull().sum()

SK_ID_CURR                      0
TARGET                          0
CNT_CHILDREN                    0
DAYS_BIRTH                      0
DAYS_EMPLOYED                   0
DAYS_ID_PUBLISH                 0
FLAG_MOBIL                      0
FLAG_EMP_PHONE                  0
FLAG_WORK_PHONE                 0
FLAG_CONT_MOBILE                0
FLAG_PHONE                      0
FLAG_EMAIL                      0
REGION_RATING_CLIENT            0
REGION_RATING_CLIENT_W_CITY     0
HOUR_APPR_PROCESS_START         0
REG_REGION_NOT_LIVE_REGION      0
REG_REGION_NOT_WORK_REGION      0
LIVE_REGION_NOT_WORK_REGION     0
REG_CITY_NOT_LIVE_CITY          0
REG_CITY_NOT_WORK_CITY          0
LIVE_CITY_NOT_WORK_CITY         0
FLAG_DOCUMENT_2                 0
FLAG_DOCUMENT_3                 0
FLAG_DOCUMENT_4                 0
FLAG_DOCUMENT_5                 0
FLAG_DOCUMENT_6                 0
FLAG_DOCUMENT_7                 0
FLAG_DOCUMENT_8                 0
FLAG_DOCUMENT_9                 0
FLAG_DOCUMENT_10                0
FLAG_DOCUMENT_11                0
FLAG_DOCUMENT_12                0
FLAG_DOCUMENT_13                0
FLAG_DOCUMENT_14                0
FLAG_DOCUMENT_15                0
FLAG_DOCUMENT_16                0
FLAG_DOCUMENT_17                0
FLAG_DOCUMENT_18                0
FLAG_DOCUMENT_19                0
FLAG_DOCUMENT_20                0
FLAG_DOCUMENT_21                0
AMT_INCOME_TOTAL                0
AMT_CREDIT                      0
AMT_ANNUITY                     0
AMT_GOODS_PRICE                 0
REGION_POPULATION_RELATIVE      0
DAYS_REGISTRATION               0
CNT_FAM_MEMBERS                 0
EXT_SOURCE_1                    0
EXT_SOURCE_2                    0
EXT_SOURCE_3                    0
APARTMENTS_AVG                  0
YEARS_BEGINEXPLUATATION_AVG     0
ELEVATORS_AVG                   0
ENTRANCES_AVG                   0
FLOORSMAX_AVG                   0
LIVINGAREA_AVG                  0
NONLIVINGAREA_AVG               0
APARTMENTS_MODE                 0
YEARS_BEGINEXPLUATATION_MODE    0
ELEVATORS_MODE                  0
ENTRANCES_MODE                  0
FLOORSMAX_MODE                  0
LIVINGAREA_MODE                 0
NONLIVINGAREA_MODE              0
APARTMENTS_MEDI                 0
YEARS_BEGINEXPLUATATION_MEDI    0
ELEVATORS_MEDI                  0
ENTRANCES_MEDI                  0
FLOORSMAX_MEDI                  0
LIVINGAREA_MEDI                 0
NONLIVINGAREA_MEDI              0
TOTALAREA_MODE                  0
OBS_30_CNT_SOCIAL_CIRCLE        0
DEF_30_CNT_SOCIAL_CIRCLE        0
OBS_60_CNT_SOCIAL_CIRCLE        0
DEF_60_CNT_SOCIAL_CIRCLE        0
DAYS_LAST_PHONE_CHANGE          0
AMT_REQ_CREDIT_BUREAU_HOUR      0
AMT_REQ_CREDIT_BUREAU_DAY       0
AMT_REQ_CREDIT_BUREAU_WEEK      0
AMT_REQ_CREDIT_BUREAU_MON       0
AMT_REQ_CREDIT_BUREAU_QRT       0
AMT_REQ_CREDIT_BUREAU_YEAR      0
NAME_CONTRACT_TYPE              0
CODE_GENDER                     0
FLAG_OWN_CAR                    0
FLAG_OWN_REALTY                 0
NAME_TYPE_SUITE                 0
NAME_INCOME_TYPE                0
NAME_EDUCATION_TYPE             0
NAME_FAMILY_STATUS              0
NAME_HOUSING_TYPE               0
OCCUPATION_TYPE                 0
WEEKDAY_APPR_PROCESS_START      0
ORGANIZATION_TYPE               0
HOUSETYPE_MODE                  0
WALLSMATERIAL_MODE              0
EMERGENCYSTATE_MODE             0
dtype: int64

In [24]:
new_app_data=pl.from_pandas(new_app_data)
new_app_data.head()

shape: (5, 99)
┌────────────┬────────┬────────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ SK_ID_CURR ┆ TARGET ┆ CNT_CHILDR ┆ DAYS_BIRT ┆ … ┆ ORGANIZAT ┆ HOUSETYPE ┆ WALLSMATE ┆ EMERGENCY │
│ ---        ┆ ---    ┆ EN         ┆ H         ┆   ┆ ION_TYPE  ┆ _MODE     ┆ RIAL_MODE ┆ STATE_MOD │
│ f64        ┆ f64    ┆ ---        ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ E         │
│            ┆        ┆ f64        ┆ f64       ┆   ┆ str       ┆ str       ┆ str       ┆ ---       │
│            ┆        ┆            ┆           ┆   ┆           ┆           ┆           ┆ str       │
╞════════════╪════════╪════════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 100002.0   ┆ 1.0    ┆ 0.0        ┆ -9461.0   ┆ … ┆ Business  ┆ block of  ┆ Stone,    ┆ No        │
│            ┆        ┆            ┆           ┆   ┆ Entity    ┆ flats     ┆ brick     ┆           │
│            ┆        ┆            ┆           ┆   ┆ Type 3    ┆           ┆           ┆           │
│ 100003.0   ┆ 0.0    ┆ 0.0        ┆ -16765.0  ┆ … ┆ School    ┆ block of  ┆ Block     ┆ No        │
│            ┆        ┆            ┆           ┆   ┆           ┆ flats     ┆           ┆           │
│ 100004.0   ┆ 0.0    ┆ 0.0        ┆ -19046.0  ┆ … ┆ Governmen ┆ block of  ┆ Panel     ┆ No        │
│            ┆        ┆            ┆           ┆   ┆ t         ┆ flats     ┆           ┆           │
│ 100006.0   ┆ 0.0    ┆ 0.0        ┆ -19005.0  ┆ … ┆ Business  ┆ block of  ┆ Panel     ┆ No        │
│            ┆        ┆            ┆           ┆   ┆ Entity    ┆ flats     ┆           ┆           │
│            ┆        ┆            ┆           ┆   ┆ Type 3    ┆           ┆           ┆           │
│ 100007.0   ┆ 0.0    ┆ 0.0        ┆ -19932.0  ┆ … ┆ Religion  ┆ block of  ┆ Panel     ┆ No        │
│            ┆        ┆            ┆           ┆   ┆           ┆ flats     ┆           ┆           │
└────────────┴────────┴────────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

# Repeated Data

In [25]:
new_app_data=new_app_data.to_pandas()

In [26]:
column_drop=["TARGET","AMT_REQ_CREDIT_BUREAU_HOUR","AMT_REQ_CREDIT_BUREAU_QRT","AMT_REQ_CREDIT_BUREAU_MON","NAME_CONTRACT_TYPE"
            ,"AMT_REQ_CREDIT_BUREAU_DAY","AMT_REQ_CREDIT_BUREAU_WEEK"]
x=new_app_data.drop(columns=column_drop,axis=1)
y=new_app_data[column_drop]

In [27]:
y.head()

,TARGET,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_MON,NAME_CONTRACT_TYPE,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK
0,1.0,0.0,0.0,0.0,Cash loans,0.0,0.0
1,0.0,0.0,0.0,0.0,Cash loans,0.0,0.0
2,0.0,0.0,0.0,0.0,Revolving loans,0.0,0.0
3,0.0,0.0,0.0,0.0,Cash loans,0.0,0.0
4,0.0,0.0,0.0,0.0,Cash loans,0.0,0.0

In [28]:
def dropping_var_wth_same_value_80_time(count_df, df):
    highest_freq_percentage = (count_df['count']/df.count()[0]).reset_index().sort_values(by = ['count'], ascending = False).iloc[0,1]
    if highest_freq_percentage >= 0.8:
        print('we will drop the column ', count_df.columns[0])
        df = df.drop(columns = [count_df.columns[0]])
    return df
df_list = []
for col in list(set(x.columns) - set(['SK_ID_CURR'])):
    df_list.append(x.groupby([col])['SK_ID_CURR'].count().reset_index().rename(columns = {'SK_ID_CURR' : 'count'}))

In [29]:
for idx in range(len(df_list)):
    print(idx)
    x = dropping_var_wth_same_value_80_time(df_list[idx], x)

0
we will drop the column  FLAG_DOCUMENT_17

C:\Users\youss\AppData\Local\Temp\ipykernel_25244\4280369097.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  highest_freq_percentage = (count_df['count']/df.count()[0]).reset_index().sort_values(by = ['count'], ascending = False).iloc[0,1]

1
2

C:\Users\youss\AppData\Local\Temp\ipykernel_25244\4280369097.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  highest_freq_percentage = (count_df['count']/df.count()[0]).reset_index().sort_values(by = ['count'], ascending = False).iloc[0,1]
C:\Users\youss\AppData\Local\Temp\ipykernel_25244\4280369097.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  highest_freq_percentage = (count_df['count']/df.count()[0]).reset_index().sort_values(by = ['count'], ascending = False).iloc[0,1]

we will drop the column  FLAG_DOCUMENT_11
3

C:\Users\youss\AppData\Local\Temp\ipykernel_25244\4280369097.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  highest_freq_percentage = (count_df['count']/df.count()[0]).reset_index().sort_values(by = ['count'], ascending = False).iloc[0,1]

we will drop the column  FLAG_DOCUMENT_2
4

C:\Users\youss\AppData\Local\Temp\ipykernel_25244\4280369097.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  highest_freq_percentage = (count_df['count']/df.count()[0]).reset_index().sort_values(by = ['count'], ascending = False).iloc[0,1]
C:\Users\youss\AppData\Local\Temp\ipykernel_25244\4280369097.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  highest_freq_percentage = (count_df['count']/df.count()[0]).reset_index().sort_values(by = ['count'], ascending = False).iloc[0,1]

5
6

C:\Users\youss\AppData\Local\Temp\ipykernel_25244\4280369097.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  highest_freq_percentage = (count_df['count']/df.count()[0]).reset_index().sort_values(by = ['count'], ascending = False).iloc[0,1]

we will drop the column  FLAG_MOBIL
7

C:\Users\youss\AppData\Local\Temp\ipykernel_25244\4280369097.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  highest_freq_percentage = (count_df['count']/df.count()[0]).reset_index().sort_values(by = ['count'], ascending = False).iloc[0,1]

we will drop the column  LIVE_REGION_NOT_WORK_REGION
8

C:\Users\youss\AppData\Local\Temp\ipykernel_25244\4280369097.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  highest_freq_percentage = (count_df['count']/df.count()[0]).reset_index().sort_values(by = ['count'], ascending = False).iloc[0,1]
C:\Users\youss\AppData\Local\Temp\ipykernel_25244\4280369097.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  highest_freq_percentage = (count_df['count']/df.count()[0]).reset_index().sort_values(by = ['count'], ascending = False).iloc[0,1]

9
10

C:\Users\youss\AppData\Local\Temp\ipykernel_25244\4280369097.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  highest_freq_percentage = (count_df['count']/df.count()[0]).reset_index().sort_values(by = ['count'], ascending = False).iloc[0,1]
C:\Users\youss\AppData\Local\Temp\ipykernel_25244\4280369097.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  highest_freq_percentage = (count_df['count']/df.count()[0]).reset_index().sort_values(by = ['count'], ascending = False).iloc[0,1]

we will drop the column  FLAG_DOCUMENT_18
11
we will drop the column  FLAG_DOCUMENT_14
12
13

C:\Users\youss\AppData\Local\Temp\ipykernel_25244\4280369097.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  highest_freq_percentage = (count_df['count']/df.count()[0]).reset_index().sort_values(by = ['count'], ascending = False).iloc[0,1]
C:\Users\youss\AppData\Local\Temp\ipykernel_25244\4280369097.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  highest_freq_percentage = (count_df['count']/df.count()[0]).reset_index().sort_values(by = ['count'], ascending = False).iloc[0,1]

we will drop the column  FLAG_DOCUMENT_6
14

C:\Users\youss\AppData\Local\Temp\ipykernel_25244\4280369097.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  highest_freq_percentage = (count_df['count']/df.count()[0]).reset_index().sort_values(by = ['count'], ascending = False).iloc[0,1]
C:\Users\youss\AppData\Local\Temp\ipykernel_25244\4280369097.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  highest_freq_percentage = (count_df['count']/df.count()[0]).reset_index().sort_values(by = ['count'], ascending = False).iloc[0,1]

15
16

C:\Users\youss\AppData\Local\Temp\ipykernel_25244\4280369097.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  highest_freq_percentage = (count_df['count']/df.count()[0]).reset_index().sort_values(by = ['count'], ascending = False).iloc[0,1]
C:\Users\youss\AppData\Local\Temp\ipykernel_25244\4280369097.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  highest_freq_percentage = (count_df['count']/df.count()[0]).reset_index().sort_values(by = ['count'], ascending = False).iloc[0,1]

17
18

C:\Users\youss\AppData\Local\Temp\ipykernel_25244\4280369097.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  highest_freq_percentage = (count_df['count']/df.count()[0]).reset_index().sort_values(by = ['count'], ascending = False).iloc[0,1]
C:\Users\youss\AppData\Local\Temp\ipykernel_25244\4280369097.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  highest_freq_percentage = (count_df['count']/df.count()[0]).reset_index().sort_values(by = ['count'], ascending = False).iloc[0,1]

we will drop the column  FLAG_EMP_PHONE
19
20

C:\Users\youss\AppData\Local\Temp\ipykernel_25244\4280369097.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  highest_freq_percentage = (count_df['count']/df.count()[0]).reset_index().sort_values(by = ['count'], ascending = False).iloc[0,1]
C:\Users\youss\AppData\Local\Temp\ipykernel_25244\4280369097.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  highest_freq_percentage = (count_df['count']/df.count()[0]).reset_index().sort_values(by = ['count'], ascending = False).iloc[0,1]

21
we will drop the column  REG_REGION_NOT_WORK_REGION
22

C:\Users\youss\AppData\Local\Temp\ipykernel_25244\4280369097.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  highest_freq_percentage = (count_df['count']/df.count()[0]).reset_index().sort_values(by = ['count'], ascending = False).iloc[0,1]
C:\Users\youss\AppData\Local\Temp\ipykernel_25244\4280369097.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  highest_freq_percentage = (count_df['count']/df.count()[0]).reset_index().sort_values(by = ['count'], ascending = False).iloc[0,1]

23
24

C:\Users\youss\AppData\Local\Temp\ipykernel_25244\4280369097.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  highest_freq_percentage = (count_df['count']/df.count()[0]).reset_index().sort_values(by = ['count'], ascending = False).iloc[0,1]
C:\Users\youss\AppData\Local\Temp\ipykernel_25244\4280369097.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  highest_freq_percentage = (count_df['count']/df.count()[0]).reset_index().sort_values(by = ['count'], ascending = False).iloc[0,1]

25
26

C:\Users\youss\AppData\Local\Temp\ipykernel_25244\4280369097.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  highest_freq_percentage = (count_df['count']/df.count()[0]).reset_index().sort_values(by = ['count'], ascending = False).iloc[0,1]
C:\Users\youss\AppData\Local\Temp\ipykernel_25244\4280369097.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  highest_freq_percentage = (count_df['count']/df.count()[0]).reset_index().sort_values(by = ['count'], ascending = False).iloc[0,1]

we will drop the column  DEF_60_CNT_SOCIAL_CIRCLE
27
28

C:\Users\youss\AppData\Local\Temp\ipykernel_25244\4280369097.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  highest_freq_percentage = (count_df['count']/df.count()[0]).reset_index().sort_values(by = ['count'], ascending = False).iloc[0,1]
C:\Users\youss\AppData\Local\Temp\ipykernel_25244\4280369097.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  highest_freq_percentage = (count_df['count']/df.count()[0]).reset_index().sort_values(by = ['count'], ascending = False).iloc[0,1]

we will drop the column  HOUSETYPE_MODE
29
we will drop the column  REG_CITY_NOT_LIVE_CITY
30
31

C:\Users\youss\AppData\Local\Temp\ipykernel_25244\4280369097.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  highest_freq_percentage = (count_df['count']/df.count()[0]).reset_index().sort_values(by = ['count'], ascending = False).iloc[0,1]
C:\Users\youss\AppData\Local\Temp\ipykernel_25244\4280369097.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  highest_freq_percentage = (count_df['count']/df.count()[0]).reset_index().sort_values(by = ['count'], ascending = False).iloc[0,1]

32
33

C:\Users\youss\AppData\Local\Temp\ipykernel_25244\4280369097.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  highest_freq_percentage = (count_df['count']/df.count()[0]).reset_index().sort_values(by = ['count'], ascending = False).iloc[0,1]
C:\Users\youss\AppData\Local\Temp\ipykernel_25244\4280369097.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  highest_freq_percentage = (count_df['count']/df.count()[0]).reset_index().sort_values(by = ['count'], ascending = False).iloc[0,1]

we will drop the column  DEF_30_CNT_SOCIAL_CIRCLE
34

C:\Users\youss\AppData\Local\Temp\ipykernel_25244\4280369097.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  highest_freq_percentage = (count_df['count']/df.count()[0]).reset_index().sort_values(by = ['count'], ascending = False).iloc[0,1]
C:\Users\youss\AppData\Local\Temp\ipykernel_25244\4280369097.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  highest_freq_percentage = (count_df['count']/df.count()[0]).reset_index().sort_values(by = ['count'], ascending = False).iloc[0,1]

35
36

C:\Users\youss\AppData\Local\Temp\ipykernel_25244\4280369097.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  highest_freq_percentage = (count_df['count']/df.count()[0]).reset_index().sort_values(by = ['count'], ascending = False).iloc[0,1]
C:\Users\youss\AppData\Local\Temp\ipykernel_25244\4280369097.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  highest_freq_percentage = (count_df['count']/df.count()[0]).reset_index().sort_values(by = ['count'], ascending = False).iloc[0,1]

37
we will drop the column  NAME_HOUSING_TYPE
38

C:\Users\youss\AppData\Local\Temp\ipykernel_25244\4280369097.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  highest_freq_percentage = (count_df['count']/df.count()[0]).reset_index().sort_values(by = ['count'], ascending = False).iloc[0,1]
C:\Users\youss\AppData\Local\Temp\ipykernel_25244\4280369097.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  highest_freq_percentage = (count_df['count']/df.count()[0]).reset_index().sort_values(by = ['count'], ascending = False).iloc[0,1]

39
40

C:\Users\youss\AppData\Local\Temp\ipykernel_25244\4280369097.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  highest_freq_percentage = (count_df['count']/df.count()[0]).reset_index().sort_values(by = ['count'], ascending = False).iloc[0,1]
C:\Users\youss\AppData\Local\Temp\ipykernel_25244\4280369097.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  highest_freq_percentage = (count_df['count']/df.count()[0]).reset_index().sort_values(by = ['count'], ascending = False).iloc[0,1]

41
42

C:\Users\youss\AppData\Local\Temp\ipykernel_25244\4280369097.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  highest_freq_percentage = (count_df['count']/df.count()[0]).reset_index().sort_values(by = ['count'], ascending = False).iloc[0,1]
C:\Users\youss\AppData\Local\Temp\ipykernel_25244\4280369097.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  highest_freq_percentage = (count_df['count']/df.count()[0]).reset_index().sort_values(by = ['count'], ascending = False).iloc[0,1]

43
we will drop the column  FLAG_DOCUMENT_20
44

C:\Users\youss\AppData\Local\Temp\ipykernel_25244\4280369097.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  highest_freq_percentage = (count_df['count']/df.count()[0]).reset_index().sort_values(by = ['count'], ascending = False).iloc[0,1]
C:\Users\youss\AppData\Local\Temp\ipykernel_25244\4280369097.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  highest_freq_percentage = (count_df['count']/df.count()[0]).reset_index().sort_values(by = ['count'], ascending = False).iloc[0,1]

45
46

C:\Users\youss\AppData\Local\Temp\ipykernel_25244\4280369097.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  highest_freq_percentage = (count_df['count']/df.count()[0]).reset_index().sort_values(by = ['count'], ascending = False).iloc[0,1]
C:\Users\youss\AppData\Local\Temp\ipykernel_25244\4280369097.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  highest_freq_percentage = (count_df['count']/df.count()[0]).reset_index().sort_values(by = ['count'], ascending = False).iloc[0,1]

we will drop the column  FLAG_DOCUMENT_9
47
we will drop the column  FLAG_DOCUMENT_16
48

C:\Users\youss\AppData\Local\Temp\ipykernel_25244\4280369097.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  highest_freq_percentage = (count_df['count']/df.count()[0]).reset_index().sort_values(by = ['count'], ascending = False).iloc[0,1]
C:\Users\youss\AppData\Local\Temp\ipykernel_25244\4280369097.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  highest_freq_percentage = (count_df['count']/df.count()[0]).reset_index().sort_values(by = ['count'], ascending = False).iloc[0,1]

we will drop the column  EMERGENCYSTATE_MODE
49
50

C:\Users\youss\AppData\Local\Temp\ipykernel_25244\4280369097.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  highest_freq_percentage = (count_df['count']/df.count()[0]).reset_index().sort_values(by = ['count'], ascending = False).iloc[0,1]
C:\Users\youss\AppData\Local\Temp\ipykernel_25244\4280369097.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  highest_freq_percentage = (count_df['count']/df.count()[0]).reset_index().sort_values(by = ['count'], ascending = False).iloc[0,1]
C:\Users\youss\AppData\Local\Temp\ipykernel_25244\4280369097.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  highest_freq_percentage = (count_df['count']/df.count()[0]).reset_index().sort_values(by = ['count'], ascending = False).iloc[0,1]

51
52
53

C:\Users\youss\AppData\Local\Temp\ipykernel_25244\4280369097.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  highest_freq_percentage = (count_df['count']/df.count()[0]).reset_index().sort_values(by = ['count'], ascending = False).iloc[0,1]
C:\Users\youss\AppData\Local\Temp\ipykernel_25244\4280369097.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  highest_freq_percentage = (count_df['count']/df.count()[0]).reset_index().sort_values(by = ['count'], ascending = False).iloc[0,1]

54
we will drop the column  FLAG_DOCUMENT_4
55

C:\Users\youss\AppData\Local\Temp\ipykernel_25244\4280369097.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  highest_freq_percentage = (count_df['count']/df.count()[0]).reset_index().sort_values(by = ['count'], ascending = False).iloc[0,1]
C:\Users\youss\AppData\Local\Temp\ipykernel_25244\4280369097.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  highest_freq_percentage = (count_df['count']/df.count()[0]).reset_index().sort_values(by = ['count'], ascending = False).iloc[0,1]

56
57

C:\Users\youss\AppData\Local\Temp\ipykernel_25244\4280369097.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  highest_freq_percentage = (count_df['count']/df.count()[0]).reset_index().sort_values(by = ['count'], ascending = False).iloc[0,1]
C:\Users\youss\AppData\Local\Temp\ipykernel_25244\4280369097.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  highest_freq_percentage = (count_df['count']/df.count()[0]).reset_index().sort_values(by = ['count'], ascending = False).iloc[0,1]

58
we will drop the column  FLAG_DOCUMENT_7
59

C:\Users\youss\AppData\Local\Temp\ipykernel_25244\4280369097.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  highest_freq_percentage = (count_df['count']/df.count()[0]).reset_index().sort_values(by = ['count'], ascending = False).iloc[0,1]
C:\Users\youss\AppData\Local\Temp\ipykernel_25244\4280369097.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  highest_freq_percentage = (count_df['count']/df.count()[0]).reset_index().sort_values(by = ['count'], ascending = False).iloc[0,1]

60
we will drop the column  REG_REGION_NOT_LIVE_REGION
61

C:\Users\youss\AppData\Local\Temp\ipykernel_25244\4280369097.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  highest_freq_percentage = (count_df['count']/df.count()[0]).reset_index().sort_values(by = ['count'], ascending = False).iloc[0,1]
C:\Users\youss\AppData\Local\Temp\ipykernel_25244\4280369097.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  highest_freq_percentage = (count_df['count']/df.count()[0]).reset_index().sort_values(by = ['count'], ascending = False).iloc[0,1]

we will drop the column  FLAG_DOCUMENT_5
62
we will drop the column  LIVE_CITY_NOT_WORK_CITY
63

C:\Users\youss\AppData\Local\Temp\ipykernel_25244\4280369097.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  highest_freq_percentage = (count_df['count']/df.count()[0]).reset_index().sort_values(by = ['count'], ascending = False).iloc[0,1]
C:\Users\youss\AppData\Local\Temp\ipykernel_25244\4280369097.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  highest_freq_percentage = (count_df['count']/df.count()[0]).reset_index().sort_values(by = ['count'], ascending = False).iloc[0,1]

we will drop the column  FLAG_DOCUMENT_15
64
we will drop the column  FLAG_DOCUMENT_19
65
66

C:\Users\youss\AppData\Local\Temp\ipykernel_25244\4280369097.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  highest_freq_percentage = (count_df['count']/df.count()[0]).reset_index().sort_values(by = ['count'], ascending = False).iloc[0,1]
C:\Users\youss\AppData\Local\Temp\ipykernel_25244\4280369097.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  highest_freq_percentage = (count_df['count']/df.count()[0]).reset_index().sort_values(by = ['count'], ascending = False).iloc[0,1]

we will drop the column  FLAG_DOCUMENT_13
67
68

C:\Users\youss\AppData\Local\Temp\ipykernel_25244\4280369097.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  highest_freq_percentage = (count_df['count']/df.count()[0]).reset_index().sort_values(by = ['count'], ascending = False).iloc[0,1]
C:\Users\youss\AppData\Local\Temp\ipykernel_25244\4280369097.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  highest_freq_percentage = (count_df['count']/df.count()[0]).reset_index().sort_values(by = ['count'], ascending = False).iloc[0,1]

we will drop the column  FLAG_CONT_MOBILE
69
70

C:\Users\youss\AppData\Local\Temp\ipykernel_25244\4280369097.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  highest_freq_percentage = (count_df['count']/df.count()[0]).reset_index().sort_values(by = ['count'], ascending = False).iloc[0,1]
C:\Users\youss\AppData\Local\Temp\ipykernel_25244\4280369097.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  highest_freq_percentage = (count_df['count']/df.count()[0]).reset_index().sort_values(by = ['count'], ascending = False).iloc[0,1]

71
we will drop the column  FLAG_DOCUMENT_21
72

C:\Users\youss\AppData\Local\Temp\ipykernel_25244\4280369097.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  highest_freq_percentage = (count_df['count']/df.count()[0]).reset_index().sort_values(by = ['count'], ascending = False).iloc[0,1]
C:\Users\youss\AppData\Local\Temp\ipykernel_25244\4280369097.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  highest_freq_percentage = (count_df['count']/df.count()[0]).reset_index().sort_values(by = ['count'], ascending = False).iloc[0,1]

73
we will drop the column  FLAG_DOCUMENT_8
74

C:\Users\youss\AppData\Local\Temp\ipykernel_25244\4280369097.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  highest_freq_percentage = (count_df['count']/df.count()[0]).reset_index().sort_values(by = ['count'], ascending = False).iloc[0,1]
C:\Users\youss\AppData\Local\Temp\ipykernel_25244\4280369097.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  highest_freq_percentage = (count_df['count']/df.count()[0]).reset_index().sort_values(by = ['count'], ascending = False).iloc[0,1]

75
76

C:\Users\youss\AppData\Local\Temp\ipykernel_25244\4280369097.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  highest_freq_percentage = (count_df['count']/df.count()[0]).reset_index().sort_values(by = ['count'], ascending = False).iloc[0,1]
C:\Users\youss\AppData\Local\Temp\ipykernel_25244\4280369097.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  highest_freq_percentage = (count_df['count']/df.count()[0]).reset_index().sort_values(by = ['count'], ascending = False).iloc[0,1]

77
78
79

C:\Users\youss\AppData\Local\Temp\ipykernel_25244\4280369097.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  highest_freq_percentage = (count_df['count']/df.count()[0]).reset_index().sort_values(by = ['count'], ascending = False).iloc[0,1]
C:\Users\youss\AppData\Local\Temp\ipykernel_25244\4280369097.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  highest_freq_percentage = (count_df['count']/df.count()[0]).reset_index().sort_values(by = ['count'], ascending = False).iloc[0,1]
C:\Users\youss\AppData\Local\Temp\ipykernel_25244\4280369097.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  highest_freq_percentage = (count_df['count']/df.count()[0]).reset_index().sort_values(by = ['count'], ascending = False).iloc[0,1]
C:\Users\youss\AppData\Local\Temp\ipykernel_25244\4280369097.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  highest_freq_percentage = (count_df['count']/df.count()[0]).reset_index().sort_values(by = ['count'], ascending = False).iloc[0,1]
C:\Users\youss\AppData\Local\Temp\ipykernel_25244\4280369097.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  highest_freq_percentage = (count_df['count']/df.count()[0]).reset_index().sort_values(by = ['count'], ascending = False).iloc[0,1]

80
81
we will drop the column  FLAG_DOCUMENT_10
82
83
84

C:\Users\youss\AppData\Local\Temp\ipykernel_25244\4280369097.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  highest_freq_percentage = (count_df['count']/df.count()[0]).reset_index().sort_values(by = ['count'], ascending = False).iloc[0,1]
C:\Users\youss\AppData\Local\Temp\ipykernel_25244\4280369097.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  highest_freq_percentage = (count_df['count']/df.count()[0]).reset_index().sort_values(by = ['count'], ascending = False).iloc[0,1]
C:\Users\youss\AppData\Local\Temp\ipykernel_25244\4280369097.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  highest_freq_percentage = (count_df['count']/df.count()[0]).reset_index().sort_values(by = ['count'], ascending = False).iloc[0,1]
C:\Users\youss\AppData\Local\Temp\ipykernel_25244\4280369097.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  highest_freq_percentage = (count_df['count']/df.count()[0]).reset_index().sort_values(by = ['count'], ascending = False).iloc[0,1]

we will drop the column  NAME_TYPE_SUITE
85
we will drop the column  FLAG_WORK_PHONE
86

C:\Users\youss\AppData\Local\Temp\ipykernel_25244\4280369097.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  highest_freq_percentage = (count_df['count']/df.count()[0]).reset_index().sort_values(by = ['count'], ascending = False).iloc[0,1]
C:\Users\youss\AppData\Local\Temp\ipykernel_25244\4280369097.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  highest_freq_percentage = (count_df['count']/df.count()[0]).reset_index().sort_values(by = ['count'], ascending = False).iloc[0,1]
C:\Users\youss\AppData\Local\Temp\ipykernel_25244\4280369097.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  highest_freq_percentage = (count_df['count']/df.count()[0]).reset_index().sort_values(by = ['count'], ascending = False).iloc[0,1]

87
88
89
we will drop the column  FLAG_DOCUMENT_12
90
we will drop the column  FLAG_EMAIL

C:\Users\youss\AppData\Local\Temp\ipykernel_25244\4280369097.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  highest_freq_percentage = (count_df['count']/df.count()[0]).reset_index().sort_values(by = ['count'], ascending = False).iloc[0,1]
C:\Users\youss\AppData\Local\Temp\ipykernel_25244\4280369097.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  highest_freq_percentage = (count_df['count']/df.count()[0]).reset_index().sort_values(by = ['count'], ascending = False).iloc[0,1]

In [30]:
x.shape

(307511, 57)

In [31]:
x.head()

,SK_ID_CURR,CNT_CHILDREN,DAYS_BIRTH,DAYS_EMPLOYED,DAYS_ID_PUBLISH,FLAG_PHONE,REGION_RATING_CLIENT,REGION_RATING_CLIENT_W_CITY,HOUR_APPR_PROCESS_START,REG_CITY_NOT_WORK_CITY,FLAG_DOCUMENT_3,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,REGION_POPULATION_RELATIVE,DAYS_REGISTRATION,CNT_FAM_MEMBERS,EXT_SOURCE_1,EXT_SOURCE_2,EXT_SOURCE_3,APARTMENTS_AVG,YEARS_BEGINEXPLUATATION_AVG,ELEVATORS_AVG,ENTRANCES_AVG,FLOORSMAX_AVG,LIVINGAREA_AVG,NONLIVINGAREA_AVG,APARTMENTS_MODE,YEARS_BEGINEXPLUATATION_MODE,ELEVATORS_MODE,ENTRANCES_MODE,FLOORSMAX_MODE,LIVINGAREA_MODE,NONLIVINGAREA_MODE,APARTMENTS_MEDI,YEARS_BEGINEXPLUATATION_MEDI,ELEVATORS_MEDI,ENTRANCES_MEDI,FLOORSMAX_MEDI,LIVINGAREA_MEDI,NONLIVINGAREA_MEDI,TOTALAREA_MODE,OBS_30_CNT_SOCIAL_CIRCLE,OBS_60_CNT_SOCIAL_CIRCLE,DAYS_LAST_PHONE_CHANGE,AMT_REQ_CREDIT_BUREAU_YEAR,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,OCCUPATION_TYPE,WEEKDAY_APPR_PROCESS_START,ORGANIZATION_TYPE,WALLSMATERIAL_MODE
0,100002.0,0.0,-9461.0,-637.0,-2120.0,1.0,2.0,2.0,10.0,0.0,1.0,202500.0,406597.5,24700.5,351000.0,0.018801,-3648.0,1.0,0.083037,0.262949,0.139376,0.024700,0.972200,0.000000,0.069000,0.083300,0.019000,0.000000,0.025200,0.972200,0.000000,0.069000,0.083300,0.019800,0.000000,0.025000,0.972200,0.000000,0.069000,0.083300,0.019300,0.000000,0.014900,2.0,2.0,-1134.0,1.0,M,N,Y,Working,Secondary / secondary special,Single / not married,Laborers,WEDNESDAY,Business Entity Type 3,"Stone, brick"
1,100003.0,0.0,-16765.0,-1188.0,-291.0,1.0,1.0,1.0,11.0,0.0,1.0,270000.0,1293502.5,35698.5,1129500.0,0.003541,-1186.0,2.0,0.311267,0.622246,0.535276,0.095900,0.985100,0.080000,0.034500,0.291700,0.054900,0.009800,0.092400,0.985100,0.080600,0.034500,0.291700,0.055400,0.000000,0.096800,0.985100,0.080000,0.034500,0.291700,0.055800,0.010000,0.071400,1.0,1.0,-828.0,0.0,F,N,N,State servant,Higher education,Married,Core staff,MONDAY,School,Block
2,100004.0,0.0,-19046.0,-225.0,-2531.0,1.0,2.0,2.0,9.0,0.0,0.0,67500.0,135000.0,6750.0,135000.0,0.010032,-4260.0,1.0,0.272586,0.555912,0.729567,0.025206,0.470849,-0.000261,0.002226,0.026318,0.121398,0.005089,-0.001742,0.217779,0.003516,0.003384,0.142304,0.127024,0.000075,0.000545,0.231712,0.002464,0.031116,0.187131,0.116373,0.000110,0.114492,0.0,0.0,-815.0,0.0,M,Y,Y,Working,Secondary / secondary special,Single / not married,Laborers,MONDAY,Government,Panel
3,100006.0,0.0,-19005.0,-3039.0,-2437.0,0.0,2.0,2.0,17.0,0.0,1.0,135000.0,312682.5,29686.5,297000.0,0.008019,-9833.0,2.0,0.309425,0.650442,0.535276,0.985202,0.494045,0.029242,0.960949,0.040093,0.267515,0.023633,0.156203,0.173594,-0.013866,0.308473,0.169275,0.337387,-0.006964,0.020599,0.254179,0.011039,0.927458,0.226234,0.282553,-0.000445,0.092209,2.0,2.0,-617.0,1.0,F,N,Y,Working,Secondary / secondary special,Civil marriage,Laborers,WEDNESDAY,Business Entity Type 3,Panel
4,100007.0,0.0,-19932.0,-3038.0,-3458.0,0.0,2.0,2.0,11.0,1.0,0.0,121500.0,513000.0,21865.5,513000.0,0.028663,-4311.0,1.0,0.272085,0.322738,0.535276,0.025285,0.474059,-0.000519,-0.000514,0.029303,0.130968,0.005942,-0.001721,0.220632,0.003516,0.020376,0.157001,0.117963,0.000075,0.000545,0.239679,0.002464,0.028830,0.185531,0.102443,0.000008,0.155555,0.0,0.0,-1106.0,0.0,M,N,Y,Working,Secondary / secondary special,Single / not married,Core staff,THURSDAY,Religion,Panel

In [32]:
x.shape

(307511, 57)

In [33]:
new_app_data.head()

,SK_ID_CURR,TARGET,CNT_CHILDREN,DAYS_BIRTH,DAYS_EMPLOYED,DAYS_ID_PUBLISH,FLAG_MOBIL,FLAG_EMP_PHONE,FLAG_WORK_PHONE,FLAG_CONT_MOBILE,FLAG_PHONE,FLAG_EMAIL,REGION_RATING_CLIENT,REGION_RATING_CLIENT_W_CITY,HOUR_APPR_PROCESS_START,REG_REGION_NOT_LIVE_REGION,REG_REGION_NOT_WORK_REGION,LIVE_REGION_NOT_WORK_REGION,REG_CITY_NOT_LIVE_CITY,REG_CITY_NOT_WORK_CITY,LIVE_CITY_NOT_WORK_CITY,FLAG_DOCUMENT_2,FLAG_DOCUMENT_3,FLAG_DOCUMENT_4,FLAG_DOCUMENT_5,FLAG_DOCUMENT_6,FLAG_DOCUMENT_7,FLAG_DOCUMENT_8,FLAG_DOCUMENT_9,FLAG_DOCUMENT_10,FLAG_DOCUMENT_11,FLAG_DOCUMENT_12,FLAG_DOCUMENT_13,FLAG_DOCUMENT_14,FLAG_DOCUMENT_15,FLAG_DOCUMENT_16,FLAG_DOCUMENT_17,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,REGION_POPULATION_RELATIVE,DAYS_REGISTRATION,CNT_FAM_MEMBERS,EXT_SOURCE_1,EXT_SOURCE_2,EXT_SOURCE_3,APARTMENTS_AVG,YEARS_BEGINEXPLUATATION_AVG,ELEVATORS_AVG,ENTRANCES_AVG,FLOORSMAX_AVG,LIVINGAREA_AVG,NONLIVINGAREA_AVG,APARTMENTS_MODE,YEARS_BEGINEXPLUATATION_MODE,ELEVATORS_MODE,ENTRANCES_MODE,FLOORSMAX_MODE,LIVINGAREA_MODE,NONLIVINGAREA_MODE,APARTMENTS_MEDI,YEARS_BEGINEXPLUATATION_MEDI,ELEVATORS_MEDI,ENTRANCES_MEDI,FLOORSMAX_MEDI,LIVINGAREA_MEDI,NONLIVINGAREA_MEDI,TOTALAREA_MODE,OBS_30_CNT_SOCIAL_CIRCLE,DEF_30_CNT_SOCIAL_CIRCLE,OBS_60_CNT_SOCIAL_CIRCLE,DEF_60_CNT_SOCIAL_CIRCLE,DAYS_LAST_PHONE_CHANGE,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,NAME_TYPE_SUITE,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,NAME_HOUSING_TYPE,OCCUPATION_TYPE,WEEKDAY_APPR_PROCESS_START,ORGANIZATION_TYPE,HOUSETYPE_MODE,WALLSMATERIAL_MODE,EMERGENCYSTATE_MODE
0,100002.0,1.0,0.0,-9461.0,-637.0,-2120.0,1.0,1.0,0.0,1.0,1.0,0.0,2.0,2.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,202500.0,406597.5,24700.5,351000.0,0.018801,-3648.0,1.0,0.083037,0.262949,0.139376,0.024700,0.972200,0.000000,0.069000,0.083300,0.019000,0.000000,0.025200,0.972200,0.000000,0.069000,0.083300,0.019800,0.000000,0.025000,0.972200,0.000000,0.069000,0.083300,0.019300,0.000000,0.014900,2.0,2.0,2.0,2.0,-1134.0,0.0,0.0,0.0,0.0,0.0,1.0,Cash loans,M,N,Y,Unaccompanied,Working,Secondary / secondary special,Single / not married,House / apartment,Laborers,WEDNESDAY,Business Entity Type 3,block of flats,"Stone, brick",No
1,100003.0,0.0,0.0,-16765.0,-1188.0,-291.0,1.0,1.0,0.0,1.0,1.0,0.0,1.0,1.0,11.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,270000.0,1293502.5,35698.5,1129500.0,0.003541,-1186.0,2.0,0.311267,0.622246,0.535276,0.095900,0.985100,0.080000,0.034500,0.291700,0.054900,0.009800,0.092400,0.985100,0.080600,0.034500,0.291700,0.055400,0.000000,0.096800,0.985100,0.080000,0.034500,0.291700,0.055800,0.010000,0.071400,1.0,0.0,1.0,0.0,-828.0,0.0,0.0,0.0,0.0,0.0,0.0,Cash loans,F,N,N,Family,State servant,Higher education,Married,House / apartment,Core staff,MONDAY,School,block of flats,Block,No
2,100004.0,0.0,0.0,-19046.0,-225.0,-2531.0,1.0,1.0,1.0,1.0,1.0,0.0,2.0,2.0,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,67500.0,135000.0,6750.0,135000.0,0.010032,-4260.0,1.0,0.272586,0.555912,0.729567,0.025206,0.470849,-0.000261,0.002226,0.026318,0.121398,0.005089,-0.001742,0.217779,0.003516,0.003384,0.142304,0.127024,0.000075,0.000545,0.231712,0.002464,0.031116,0.187131,0.116373,0.000110,0.114492,0.0,0.0,0.0,0.0,-815.0,0.0,0.0,0.0,0.0,0.0,0.0,Revolving loans,M,Y,Y,Unaccompanied,Working,Secondary / secondary special,Single / not married,House / apartment,Laborers,MONDAY,Government,block of flats,Panel,No
3,100006.0,0.0,0.0,-19005.0,-3039.0,-2437.0,1.0,1.0,0.0,1.0,0.0,0.0,2.0,2.0,17.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,135000.0,312682.5,29686.5,297000.0,0.008019,-9833.0,2.0,0.309425,0.650442,0.535276,0.985202,0.494045,0.029242,0.960949,0.040093,0.267515,0.023633,0.156203,0.173594,-0.013866,0.308473,0.169275,0.337387,-0.006964,0.020599,0.254179,0.011039,0.927458,0.226234,0.282553,-0.000445,0.092209,2.0,0.0,2.0,0.0,-617.0,0.0,0.0,0.0,0.0,0.0,1.0,Cash loans,F,N,Y,Unaccompanied,Working,Secondary / secondary special,Civil marriage,House / apartment,Laborers,WEDNESDAY,Business Entity Type 3,block of flats,Panel,No
4,100007.0,0.0,0.0,-19932.0,-3038.0,-3458.0,1.0,1.0,0.0,1.0,0.0,0.0,2.0,2.0,11.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,121500.0,513000.0,21865.5,513000.0,0.028663,-4311.0,1.0,0.272085,0.322738,0.535276,0.025285,0.474059,-0.000519,-0.000514,0.029303,0.130968,0.005942,-0.001721,0.220632,0.003516,0.020376,0.157001,0.117963,0.000075,0.000545,0.239679,0.002464,0.028830,0.185531,0.102443,0.000008,0.155555,0.0,0.0,0.0,0.0,-1106.0,0.0,0.0,0.0,0.0,0.0,0.0,Cash loans,M,N,Y,Unaccompanied,Working,Secondary / secondary special,Single / not married,House / apartment,Core staff,THURSDAY,Religion,block of flats,Panel,No

In [34]:
new_app_data=pd.concat([x,y],axis=1)
new_app_data.head()

,SK_ID_CURR,CNT_CHILDREN,DAYS_BIRTH,DAYS_EMPLOYED,DAYS_ID_PUBLISH,FLAG_PHONE,REGION_RATING_CLIENT,REGION_RATING_CLIENT_W_CITY,HOUR_APPR_PROCESS_START,REG_CITY_NOT_WORK_CITY,FLAG_DOCUMENT_3,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,REGION_POPULATION_RELATIVE,DAYS_REGISTRATION,CNT_FAM_MEMBERS,EXT_SOURCE_1,EXT_SOURCE_2,EXT_SOURCE_3,APARTMENTS_AVG,YEARS_BEGINEXPLUATATION_AVG,ELEVATORS_AVG,ENTRANCES_AVG,FLOORSMAX_AVG,LIVINGAREA_AVG,NONLIVINGAREA_AVG,APARTMENTS_MODE,YEARS_BEGINEXPLUATATION_MODE,ELEVATORS_MODE,ENTRANCES_MODE,FLOORSMAX_MODE,LIVINGAREA_MODE,NONLIVINGAREA_MODE,APARTMENTS_MEDI,YEARS_BEGINEXPLUATATION_MEDI,ELEVATORS_MEDI,ENTRANCES_MEDI,FLOORSMAX_MEDI,LIVINGAREA_MEDI,NONLIVINGAREA_MEDI,TOTALAREA_MODE,OBS_30_CNT_SOCIAL_CIRCLE,OBS_60_CNT_SOCIAL_CIRCLE,DAYS_LAST_PHONE_CHANGE,AMT_REQ_CREDIT_BUREAU_YEAR,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,OCCUPATION_TYPE,WEEKDAY_APPR_PROCESS_START,ORGANIZATION_TYPE,WALLSMATERIAL_MODE,TARGET,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_MON,NAME_CONTRACT_TYPE,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK
0,100002.0,0.0,-9461.0,-637.0,-2120.0,1.0,2.0,2.0,10.0,0.0,1.0,202500.0,406597.5,24700.5,351000.0,0.018801,-3648.0,1.0,0.083037,0.262949,0.139376,0.024700,0.972200,0.000000,0.069000,0.083300,0.019000,0.000000,0.025200,0.972200,0.000000,0.069000,0.083300,0.019800,0.000000,0.025000,0.972200,0.000000,0.069000,0.083300,0.019300,0.000000,0.014900,2.0,2.0,-1134.0,1.0,M,N,Y,Working,Secondary / secondary special,Single / not married,Laborers,WEDNESDAY,Business Entity Type 3,"Stone, brick",1.0,0.0,0.0,0.0,Cash loans,0.0,0.0
1,100003.0,0.0,-16765.0,-1188.0,-291.0,1.0,1.0,1.0,11.0,0.0,1.0,270000.0,1293502.5,35698.5,1129500.0,0.003541,-1186.0,2.0,0.311267,0.622246,0.535276,0.095900,0.985100,0.080000,0.034500,0.291700,0.054900,0.009800,0.092400,0.985100,0.080600,0.034500,0.291700,0.055400,0.000000,0.096800,0.985100,0.080000,0.034500,0.291700,0.055800,0.010000,0.071400,1.0,1.0,-828.0,0.0,F,N,N,State servant,Higher education,Married,Core staff,MONDAY,School,Block,0.0,0.0,0.0,0.0,Cash loans,0.0,0.0
2,100004.0,0.0,-19046.0,-225.0,-2531.0,1.0,2.0,2.0,9.0,0.0,0.0,67500.0,135000.0,6750.0,135000.0,0.010032,-4260.0,1.0,0.272586,0.555912,0.729567,0.025206,0.470849,-0.000261,0.002226,0.026318,0.121398,0.005089,-0.001742,0.217779,0.003516,0.003384,0.142304,0.127024,0.000075,0.000545,0.231712,0.002464,0.031116,0.187131,0.116373,0.000110,0.114492,0.0,0.0,-815.0,0.0,M,Y,Y,Working,Secondary / secondary special,Single / not married,Laborers,MONDAY,Government,Panel,0.0,0.0,0.0,0.0,Revolving loans,0.0,0.0
3,100006.0,0.0,-19005.0,-3039.0,-2437.0,0.0,2.0,2.0,17.0,0.0,1.0,135000.0,312682.5,29686.5,297000.0,0.008019,-9833.0,2.0,0.309425,0.650442,0.535276,0.985202,0.494045,0.029242,0.960949,0.040093,0.267515,0.023633,0.156203,0.173594,-0.013866,0.308473,0.169275,0.337387,-0.006964,0.020599,0.254179,0.011039,0.927458,0.226234,0.282553,-0.000445,0.092209,2.0,2.0,-617.0,1.0,F,N,Y,Working,Secondary / secondary special,Civil marriage,Laborers,WEDNESDAY,Business Entity Type 3,Panel,0.0,0.0,0.0,0.0,Cash loans,0.0,0.0
4,100007.0,0.0,-19932.0,-3038.0,-3458.0,0.0,2.0,2.0,11.0,1.0,0.0,121500.0,513000.0,21865.5,513000.0,0.028663,-4311.0,1.0,0.272085,0.322738,0.535276,0.025285,0.474059,-0.000519,-0.000514,0.029303,0.130968,0.005942,-0.001721,0.220632,0.003516,0.020376,0.157001,0.117963,0.000075,0.000545,0.239679,0.002464,0.028830,0.185531,0.102443,0.000008,0.155555,0.0,0.0,-1106.0,0.0,M,N,Y,Working,Secondary / secondary special,Single / not married,Core staff,THURSDAY,Religion,Panel,0.0,0.0,0.0,0.0,Cash loans,0.0,0.0

In [35]:
new_app_data.shape

(307511, 64)

# aggs

In [36]:
previous_app_data=pd.read_csv("datasets\previous_application.csv")

<>:1: SyntaxWarning: invalid escape sequence '\p'
<>:1: SyntaxWarning: invalid escape sequence '\p'
C:\Users\youss\AppData\Local\Temp\ipykernel_25244\3893482589.py:1: SyntaxWarning: invalid escape sequence '\p'
  previous_app_data=pd.read_csv("datasets\previous_application.csv")

In [37]:
def agg(column_names, type_of_agg, id, data,table_name):
    aggregated_data = data.groupby(id).agg({col: type_of_agg for col in column_names}).reset_index()
    new_column_names = {col: f"{col}_{type_of_agg}_{table_name}" for col in column_names}
    aggregated_data.rename(columns=new_column_names, inplace=True)

    return aggregated_data

In [38]:

aggs_max_columns = [
    "DAYS_DECISION",
    "CNT_PAYMENT",
    "DAYS_FIRST_DRAWING",
    "DAYS_FIRST_DUE",
    "DAYS_LAST_DUE_1ST_VERSION",
    "DAYS_LAST_DUE",
    "DAYS_TERMINATION",
    "NFLAG_INSURED_ON_APPROVAL",
]
agg_max_for_previous_columns=agg(aggs_max_columns,"mean","SK_ID_CURR",previous_app_data,"previous_app_data")
merge_max_previous_app=new_app_data.merge(agg_max_for_previous_columns,how='left',on='SK_ID_CURR')

In [39]:
new_app_data=merge_max_previous_app.copy()
new_app_data.columns

Index(['SK_ID_CURR', 'CNT_CHILDREN', 'DAYS_BIRTH', 'DAYS_EMPLOYED',
       'DAYS_ID_PUBLISH', 'FLAG_PHONE', 'REGION_RATING_CLIENT',
       'REGION_RATING_CLIENT_W_CITY', 'HOUR_APPR_PROCESS_START',
       'REG_CITY_NOT_WORK_CITY', 'FLAG_DOCUMENT_3', 'AMT_INCOME_TOTAL',
       'AMT_CREDIT', 'AMT_ANNUITY', 'AMT_GOODS_PRICE',
       'REGION_POPULATION_RELATIVE', 'DAYS_REGISTRATION', 'CNT_FAM_MEMBERS',
       'EXT_SOURCE_1', 'EXT_SOURCE_2', 'EXT_SOURCE_3', 'APARTMENTS_AVG',
       'YEARS_BEGINEXPLUATATION_AVG', 'ELEVATORS_AVG', 'ENTRANCES_AVG',
       'FLOORSMAX_AVG', 'LIVINGAREA_AVG', 'NONLIVINGAREA_AVG',
       'APARTMENTS_MODE', 'YEARS_BEGINEXPLUATATION_MODE', 'ELEVATORS_MODE',
       'ENTRANCES_MODE', 'FLOORSMAX_MODE', 'LIVINGAREA_MODE',
       'NONLIVINGAREA_MODE', 'APARTMENTS_MEDI', 'YEARS_BEGINEXPLUATATION_MEDI',
       'ELEVATORS_MEDI', 'ENTRANCES_MEDI', 'FLOORSMAX_MEDI', 'LIVINGAREA_MEDI',
       'NONLIVINGAREA_MEDI', 'TOTALAREA_MODE', 'OBS_30_CNT_SOCIAL_CIRCLE',
       'OBS_60_CNT_SOCIAL_CIRCLE', 'DAYS_LAST_PHONE_CHANGE',
       'AMT_REQ_CREDIT_BUREAU_YEAR', 'CODE_GENDER', 'FLAG_OWN_CAR',
       'FLAG_OWN_REALTY', 'NAME_INCOME_TYPE', 'NAME_EDUCATION_TYPE',
       'NAME_FAMILY_STATUS', 'OCCUPATION_TYPE', 'WEEKDAY_APPR_PROCESS_START',
       'ORGANIZATION_TYPE', 'WALLSMATERIAL_MODE', 'TARGET',
       'AMT_REQ_CREDIT_BUREAU_HOUR', 'AMT_REQ_CREDIT_BUREAU_QRT',
       'AMT_REQ_CREDIT_BUREAU_MON', 'NAME_CONTRACT_TYPE',
       'AMT_REQ_CREDIT_BUREAU_DAY', 'AMT_REQ_CREDIT_BUREAU_WEEK',
       'DAYS_DECISION_mean_previous_app_data',
       'CNT_PAYMENT_mean_previous_app_data',
       'DAYS_FIRST_DRAWING_mean_previous_app_data',
       'DAYS_FIRST_DUE_mean_previous_app_data',
       'DAYS_LAST_DUE_1ST_VERSION_mean_previous_app_data',
       'DAYS_LAST_DUE_mean_previous_app_data',
       'DAYS_TERMINATION_mean_previous_app_data',
       'NFLAG_INSURED_ON_APPROVAL_mean_previous_app_data'],
      dtype='object')

In [40]:

aggs_count_columns = ["HOUR_APPR_PROCESS_START", "NFLAG_LAST_APPL_IN_DAY", "AMT_ANNUITY"]
agg_count_for_previous_columns=agg(aggs_count_columns,"mean","SK_ID_CURR",previous_app_data,"previous_app_data")
merge_count_previous_app=new_app_data.merge(agg_count_for_previous_columns,how='left',on='SK_ID_CURR')
new_app_data=merge_count_previous_app.copy()
new_app_data.head()

,SK_ID_CURR,CNT_CHILDREN,DAYS_BIRTH,DAYS_EMPLOYED,DAYS_ID_PUBLISH,FLAG_PHONE,REGION_RATING_CLIENT,REGION_RATING_CLIENT_W_CITY,HOUR_APPR_PROCESS_START,REG_CITY_NOT_WORK_CITY,FLAG_DOCUMENT_3,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,REGION_POPULATION_RELATIVE,DAYS_REGISTRATION,CNT_FAM_MEMBERS,EXT_SOURCE_1,EXT_SOURCE_2,EXT_SOURCE_3,APARTMENTS_AVG,YEARS_BEGINEXPLUATATION_AVG,ELEVATORS_AVG,ENTRANCES_AVG,FLOORSMAX_AVG,LIVINGAREA_AVG,NONLIVINGAREA_AVG,APARTMENTS_MODE,YEARS_BEGINEXPLUATATION_MODE,ELEVATORS_MODE,ENTRANCES_MODE,FLOORSMAX_MODE,LIVINGAREA_MODE,NONLIVINGAREA_MODE,APARTMENTS_MEDI,YEARS_BEGINEXPLUATATION_MEDI,ELEVATORS_MEDI,ENTRANCES_MEDI,FLOORSMAX_MEDI,LIVINGAREA_MEDI,NONLIVINGAREA_MEDI,TOTALAREA_MODE,OBS_30_CNT_SOCIAL_CIRCLE,OBS_60_CNT_SOCIAL_CIRCLE,DAYS_LAST_PHONE_CHANGE,AMT_REQ_CREDIT_BUREAU_YEAR,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,OCCUPATION_TYPE,WEEKDAY_APPR_PROCESS_START,ORGANIZATION_TYPE,WALLSMATERIAL_MODE,TARGET,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_MON,NAME_CONTRACT_TYPE,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,DAYS_DECISION_mean_previous_app_data,CNT_PAYMENT_mean_previous_app_data,DAYS_FIRST_DRAWING_mean_previous_app_data,DAYS_FIRST_DUE_mean_previous_app_data,DAYS_LAST_DUE_1ST_VERSION_mean_previous_app_data,DAYS_LAST_DUE_mean_previous_app_data,DAYS_TERMINATION_mean_previous_app_data,NFLAG_INSURED_ON_APPROVAL_mean_previous_app_data,HOUR_APPR_PROCESS_START_mean_previous_app_data,NFLAG_LAST_APPL_IN_DAY_mean_previous_app_data,AMT_ANNUITY_mean_previous_app_data
0,100002.0,0.0,-9461.0,-637.0,-2120.0,1.0,2.0,2.0,10.0,0.0,1.0,202500.0,406597.5,24700.5,351000.0,0.018801,-3648.0,1.0,0.083037,0.262949,0.139376,0.024700,0.972200,0.000000,0.069000,0.083300,0.019000,0.000000,0.025200,0.972200,0.000000,0.069000,0.083300,0.019800,0.000000,0.025000,0.972200,0.000000,0.069000,0.083300,0.019300,0.000000,0.014900,2.0,2.0,-1134.0,1.0,M,N,Y,Working,Secondary / secondary special,Single / not married,Laborers,WEDNESDAY,Business Entity Type 3,"Stone, brick",1.0,0.0,0.0,0.0,Cash loans,0.0,0.0,-606.000000,24.000000,365243.0,-565.000000,125.000000,-25.000000,-17.000000,0.000000,9.000000,1.0,9251.775
1,100003.0,0.0,-16765.0,-1188.0,-291.0,1.0,1.0,1.0,11.0,0.0,1.0,270000.0,1293502.5,35698.5,1129500.0,0.003541,-1186.0,2.0,0.311267,0.622246,0.535276,0.095900,0.985100,0.080000,0.034500,0.291700,0.054900,0.009800,0.092400,0.985100,0.080600,0.034500,0.291700,0.055400,0.000000,0.096800,0.985100,0.080000,0.034500,0.291700,0.055800,0.010000,0.071400,1.0,1.0,-828.0,0.0,F,N,N,State servant,Higher education,Married,Core staff,MONDAY,School,Block,0.0,0.0,0.0,0.0,Cash loans,0.0,0.0,-1305.000000,10.000000,365243.0,-1274.333333,-1004.333333,-1054.333333,-1047.333333,0.666667,14.666667,1.0,56553.990
2,100004.0,0.0,-19046.0,-225.0,-2531.0,1.0,2.0,2.0,9.0,0.0,0.0,67500.0,135000.0,6750.0,135000.0,0.010032,-4260.0,1.0,0.272586,0.555912,0.729567,0.025206,0.470849,-0.000261,0.002226,0.026318,0.121398,0.005089,-0.001742,0.217779,0.003516,0.003384,0.142304,0.127024,0.000075,0.000545,0.231712,0.002464,0.031116,0.187131,0.116373,0.000110,0.114492,0.0,0.0,-815.0,0.0,M,Y,Y,Working,Secondary / secondary special,Single / not married,Laborers,MONDAY,Government,Panel,0.0,0.0,0.0,0.0,Revolving loans,0.0,0.0,-815.000000,4.000000,365243.0,-784.000000,-694.000000,-724.000000,-714.000000,0.000000,5.000000,1.0,5357.250
3,100006.0,0.0,-19005.0,-3039.0,-2437.0,0.0,2.0,2.0,17.0,0.0,1.0,135000.0,312682.5,29686.5,297000.0,0.008019,-9833.0,2.0,0.309425,0.650442,0.535276,0.985202,0.494045,0.029242,0.960949,0.040093,0.267515,0.023633,0.156203,0.173594,-0.013866,0.308473,0.169275,0.337387,-0.006964,0.020599,0.254179,0.011039,0.927458,0.226234,0.282553,-0.000445,0.092209,2.0,2.0,-617.0,1.0,F,N,Y,Working,Secondary / secondary special,Civil marriage,Laborers,WEDNESDAY,Business Entity Type 3,Panel,0.0,0.0,0.0,0.0,Cash loans,0.0,0.0,-272.444444,23.000000,365243.0,91066.500000,91584.000000,182477.500000,182481.750000,0.000000,14.666667,1.0,23651.175
4,100007.0,0.0,-19932.0,-3038.0,-3458.0,0.0,2.0,2.0,11.0,1.0,0.0,121500.0,513000.0,21865.5,513000.0,0.028663,-4311.0,1.0,0.272085,0.322738,0.535276,0.025285,0.474059,-0.000519,-0.000514,0.029303,0.130968,0.005942,-0.001721,0.220632,0.003516,0.020376,0.157001,0.117963,0.000075,0.000545,0.239679,0.002464,0.028830,0.185531,0.102443,0.000008,0.155555,0.0,0.0,-1106.0,0.0,M,N,Y,Working,Secondary / secondary special,Single / not married,Core staff,THURSDAY,Religion,Panel,0.0,0.0,0.0,0.0,Cash loans,0.0,0.0,-1222.833333,20.666667,365243.0,-1263.200000,-837.200000,72136.200000,72143.800000,0.600000,12.333333,1.0,12278.805

In [41]:

aggs_mean_columns = ["AMT_APPLICATION", "AMT_CREDIT", "AMT_DOWN_PAYMENT", "AMT_GOODS_PRICE", "RATE_DOWN_PAYMENT", "RATE_INTEREST_PRIMARY", "RATE_INTEREST_PRIVILEGED"]

agg_mean_for_previous_columns=agg(aggs_mean_columns,"mean","SK_ID_CURR",previous_app_data,"previous_app_data")
merge_mean_previous_app=new_app_data.merge(agg_mean_for_previous_columns,how='left',on='SK_ID_CURR')
new_app_data=merge_mean_previous_app.copy()

In [42]:
agg_contract = previous_app_data.groupby(['SK_ID_CURR', 'NAME_CONTRACT_TYPE']).size().reset_index(name='count')
pivot_of_contract = agg_contract.pivot_table(index='SK_ID_CURR', columns='NAME_CONTRACT_TYPE', values='count', fill_value=0)
pivot_of_contract = pivot_of_contract.rename(columns={
    "Cash loans": "Cash_loans_from__contract_from_previous_table",
    "Consumer loans": "Consumer_loans_from_contract_from_previous_table",
    "Revolving loans": "Revolving_loans_from_contract_from_previous_table",
    "XNA":"XNA_from_contract_from_previous_table"
})
merge_pivot_contract_new_app=new_app_data.merge(pivot_of_contract,how="left",on="SK_ID_CURR")
new_app_data=merge_pivot_contract_new_app.copy()
new_app_data.head()

,SK_ID_CURR,CNT_CHILDREN,DAYS_BIRTH,DAYS_EMPLOYED,DAYS_ID_PUBLISH,FLAG_PHONE,REGION_RATING_CLIENT,REGION_RATING_CLIENT_W_CITY,HOUR_APPR_PROCESS_START,REG_CITY_NOT_WORK_CITY,FLAG_DOCUMENT_3,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,REGION_POPULATION_RELATIVE,DAYS_REGISTRATION,CNT_FAM_MEMBERS,EXT_SOURCE_1,EXT_SOURCE_2,EXT_SOURCE_3,APARTMENTS_AVG,YEARS_BEGINEXPLUATATION_AVG,ELEVATORS_AVG,ENTRANCES_AVG,FLOORSMAX_AVG,LIVINGAREA_AVG,NONLIVINGAREA_AVG,APARTMENTS_MODE,YEARS_BEGINEXPLUATATION_MODE,ELEVATORS_MODE,ENTRANCES_MODE,FLOORSMAX_MODE,LIVINGAREA_MODE,NONLIVINGAREA_MODE,APARTMENTS_MEDI,YEARS_BEGINEXPLUATATION_MEDI,ELEVATORS_MEDI,ENTRANCES_MEDI,FLOORSMAX_MEDI,LIVINGAREA_MEDI,NONLIVINGAREA_MEDI,TOTALAREA_MODE,OBS_30_CNT_SOCIAL_CIRCLE,OBS_60_CNT_SOCIAL_CIRCLE,DAYS_LAST_PHONE_CHANGE,AMT_REQ_CREDIT_BUREAU_YEAR,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,OCCUPATION_TYPE,WEEKDAY_APPR_PROCESS_START,ORGANIZATION_TYPE,WALLSMATERIAL_MODE,TARGET,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_MON,NAME_CONTRACT_TYPE,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,DAYS_DECISION_mean_previous_app_data,CNT_PAYMENT_mean_previous_app_data,DAYS_FIRST_DRAWING_mean_previous_app_data,DAYS_FIRST_DUE_mean_previous_app_data,DAYS_LAST_DUE_1ST_VERSION_mean_previous_app_data,DAYS_LAST_DUE_mean_previous_app_data,DAYS_TERMINATION_mean_previous_app_data,NFLAG_INSURED_ON_APPROVAL_mean_previous_app_data,HOUR_APPR_PROCESS_START_mean_previous_app_data,NFLAG_LAST_APPL_IN_DAY_mean_previous_app_data,AMT_ANNUITY_mean_previous_app_data,AMT_APPLICATION_mean_previous_app_data,AMT_CREDIT_mean_previous_app_data,AMT_DOWN_PAYMENT_mean_previous_app_data,AMT_GOODS_PRICE_mean_previous_app_data,RATE_DOWN_PAYMENT_mean_previous_app_data,RATE_INTEREST_PRIMARY_mean_previous_app_data,RATE_INTEREST_PRIVILEGED_mean_previous_app_data,Cash_loans_from__contract_from_previous_table,Consumer_loans_from_contract_from_previous_table,Revolving_loans_from_contract_from_previous_table,XNA_from_contract_from_previous_table
0,100002.0,0.0,-9461.0,-637.0,-2120.0,1.0,2.0,2.0,10.0,0.0,1.0,202500.0,406597.5,24700.5,351000.0,0.018801,-3648.0,1.0,0.083037,0.262949,0.139376,0.024700,0.972200,0.000000,0.069000,0.083300,0.019000,0.000000,0.025200,0.972200,0.000000,0.069000,0.083300,0.019800,0.000000,0.025000,0.972200,0.000000,0.069000,0.083300,0.019300,0.000000,0.014900,2.0,2.0,-1134.0,1.0,M,N,Y,Working,Secondary / secondary special,Single / not married,Laborers,WEDNESDAY,Business Entity Type 3,"Stone, brick",1.0,0.0,0.0,0.0,Cash loans,0.0,0.0,-606.000000,24.000000,365243.0,-565.000000,125.000000,-25.000000,-17.000000,0.000000,9.000000,1.0,9251.775,179055.00,179055.00,0.00,179055.00,0.000000,NaN,NaN,0.0,1.0,0.0,0.0
1,100003.0,0.0,-16765.0,-1188.0,-291.0,1.0,1.0,1.0,11.0,0.0,1.0,270000.0,1293502.5,35698.5,1129500.0,0.003541,-1186.0,2.0,0.311267,0.622246,0.535276,0.095900,0.985100,0.080000,0.034500,0.291700,0.054900,0.009800,0.092400,0.985100,0.080600,0.034500,0.291700,0.055400,0.000000,0.096800,0.985100,0.080000,0.034500,0.291700,0.055800,0.010000,0.071400,1.0,1.0,-828.0,0.0,F,N,N,State servant,Higher education,Married,Core staff,MONDAY,School,Block,0.0,0.0,0.0,0.0,Cash loans,0.0,0.0,-1305.000000,10.000000,365243.0,-1274.333333,-1004.333333,-1054.333333,-1047.333333,0.666667,14.666667,1.0,56553.990,435436.50,484191.00,3442.50,435436.50,0.050030,NaN,NaN,1.0,2.0,0.0,0.0
2,100004.0,0.0,-19046.0,-225.0,-2531.0,1.0,2.0,2.0,9.0,0.0,0.0,67500.0,135000.0,6750.0,135000.0,0.010032,-4260.0,1.0,0.272586,0.555912,0.729567,0.025206,0.470849,-0.000261,0.002226,0.026318,0.121398,0.005089,-0.001742,0.217779,0.003516,0.003384,0.142304,0.127024,0.000075,0.000545,0.231712,0.002464,0.031116,0.187131,0.116373,0.000110,0.114492,0.0,0.0,-815.0,0.0,M,Y,Y,Working,Secondary / secondary special,Single / not married,Laborers,MONDAY,Government,Panel,0.0,0.0,0.0,0.0,Revolving loans,0.0,0.0,-815.000000,4.000000,365243.0,-784.000000,-694.000000,-724.000000,-714.000000,0.000000,5.000000,1.0,5357.250,24282.00,20106.00,4860.00,24282.00,0.212008,NaN,NaN,0.0,1.0,0.0,0.0
3,100006.0,0.0,-19005.0,-3039.0,-2437.0,0.0,2.0,2.0,17.0,0.0,1.0,135000.0,312682.5,29686.5,297000.0,0.008019,-9833.0,2.0,0.309425,0.650442,0.535276,0.985202,0.494045,0.029242,0.960949,0.040093,0.267515,0.023633,0.156203,0.173594,-0.013866,0.308473,0.169275,0.337387,-0.006964,0.020599,0.254179,0.011039,0.927458,0.226234,0.282553,-0.000445,0.092209,2.0,2.0,-617.0,1.0,F,N,Y,Working,Secondary / secondary special,Civil marriage,Laborers,WEDNESDAY,Business Entity Type 3,Panel,0.0,0.0,0.0,0.0,Cash loans,0.0,0.0,-272.444444,23.000000,365243.0,91066.500000,91584.000000,182477.500000,182481.750000,0.000000,14.666667,1.0,23651.175,272203.26,291695.50,34840.17,408304.89,0.163412,NaN,NaN,5.0,2.0,2.0,0.0
4,100007.0,0.0,-19932.0,-3038.0,-3458.0,0.0,2.0,2.0,11.0,1.0,0.0,121500.0,513000.0,21865.5,513000.0,0.028663,-4311.0,1.0,0.272085,0.322738,0.535276,0.025285,0.474059,-0.000519,-0.000514,0.029303,0.130968,0.005942,-0.001721,0.220632,0.003516,0.020376,0.157001,0.117963,0.000075,0.000545,0.239679,0.002464,0.028830,0.185531,0.102443,0.000008,0.155555,0.0,0.0,-1106.0,0.0,M,N,Y,Working,Secondary / secondary special,Single / not married,Core staff,THURSDAY,Religion,Panel,0.0,0.0,0.0,0.0,Cash loans,0.0,0.0,-1222.833333,20.666667,365243.0,-1263.200000,-837.200000,72136.200000,72143.800000,0.600000,12.333333,1.0,12278.805,150530.25,166638.75,3390.75,150530.25,0.159516,NaN,NaN,4.0,2.0,0.0,0.0

In [43]:
agg_FLAG_LAST_APPL_PER_CONTRACT = previous_app_data.groupby(['SK_ID_CURR', 'FLAG_LAST_APPL_PER_CONTRACT']).size().reset_index(name='count')
pivot_of_FLAG_LAST_APPL_PER_CONTRACT = agg_FLAG_LAST_APPL_PER_CONTRACT.pivot_table(index='SK_ID_CURR', columns='FLAG_LAST_APPL_PER_CONTRACT', values='count', fill_value=0)
pivot_of_FLAG_LAST_APPL_PER_CONTRACT = pivot_of_FLAG_LAST_APPL_PER_CONTRACT.rename(columns={
    "Y": "Y_from__FLAG_LAST_APPL_PER_CONTRACT_from_previous_table",
    "N": "N_loans_from_FLAG_LAST_APPL_PER_CONTRACT_from_previous_table",
    
})
merge_pivot_FLAG_LAST_APPL_PER_CONTRACT_new_app=new_app_data.merge(pivot_of_FLAG_LAST_APPL_PER_CONTRACT,how="left",on="SK_ID_CURR")
new_app_data=merge_pivot_FLAG_LAST_APPL_PER_CONTRACT_new_app.copy()
new_app_data.head()

,SK_ID_CURR,CNT_CHILDREN,DAYS_BIRTH,DAYS_EMPLOYED,DAYS_ID_PUBLISH,FLAG_PHONE,REGION_RATING_CLIENT,REGION_RATING_CLIENT_W_CITY,HOUR_APPR_PROCESS_START,REG_CITY_NOT_WORK_CITY,FLAG_DOCUMENT_3,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,REGION_POPULATION_RELATIVE,DAYS_REGISTRATION,CNT_FAM_MEMBERS,EXT_SOURCE_1,EXT_SOURCE_2,EXT_SOURCE_3,APARTMENTS_AVG,YEARS_BEGINEXPLUATATION_AVG,ELEVATORS_AVG,ENTRANCES_AVG,FLOORSMAX_AVG,LIVINGAREA_AVG,NONLIVINGAREA_AVG,APARTMENTS_MODE,YEARS_BEGINEXPLUATATION_MODE,ELEVATORS_MODE,ENTRANCES_MODE,FLOORSMAX_MODE,LIVINGAREA_MODE,NONLIVINGAREA_MODE,APARTMENTS_MEDI,YEARS_BEGINEXPLUATATION_MEDI,ELEVATORS_MEDI,ENTRANCES_MEDI,FLOORSMAX_MEDI,LIVINGAREA_MEDI,NONLIVINGAREA_MEDI,TOTALAREA_MODE,OBS_30_CNT_SOCIAL_CIRCLE,OBS_60_CNT_SOCIAL_CIRCLE,DAYS_LAST_PHONE_CHANGE,AMT_REQ_CREDIT_BUREAU_YEAR,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,OCCUPATION_TYPE,WEEKDAY_APPR_PROCESS_START,ORGANIZATION_TYPE,WALLSMATERIAL_MODE,TARGET,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_MON,NAME_CONTRACT_TYPE,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,DAYS_DECISION_mean_previous_app_data,CNT_PAYMENT_mean_previous_app_data,DAYS_FIRST_DRAWING_mean_previous_app_data,DAYS_FIRST_DUE_mean_previous_app_data,DAYS_LAST_DUE_1ST_VERSION_mean_previous_app_data,DAYS_LAST_DUE_mean_previous_app_data,DAYS_TERMINATION_mean_previous_app_data,NFLAG_INSURED_ON_APPROVAL_mean_previous_app_data,HOUR_APPR_PROCESS_START_mean_previous_app_data,NFLAG_LAST_APPL_IN_DAY_mean_previous_app_data,AMT_ANNUITY_mean_previous_app_data,AMT_APPLICATION_mean_previous_app_data,AMT_CREDIT_mean_previous_app_data,AMT_DOWN_PAYMENT_mean_previous_app_data,AMT_GOODS_PRICE_mean_previous_app_data,RATE_DOWN_PAYMENT_mean_previous_app_data,RATE_INTEREST_PRIMARY_mean_previous_app_data,RATE_INTEREST_PRIVILEGED_mean_previous_app_data,Cash_loans_from__contract_from_previous_table,Consumer_loans_from_contract_from_previous_table,Revolving_loans_from_contract_from_previous_table,XNA_from_contract_from_previous_table,N_loans_from_FLAG_LAST_APPL_PER_CONTRACT_from_previous_table,Y_from__FLAG_LAST_APPL_PER_CONTRACT_from_previous_table
0,100002.0,0.0,-9461.0,-637.0,-2120.0,1.0,2.0,2.0,10.0,0.0,1.0,202500.0,406597.5,24700.5,351000.0,0.018801,-3648.0,1.0,0.083037,0.262949,0.139376,0.024700,0.972200,0.000000,0.069000,0.083300,0.019000,0.000000,0.025200,0.972200,0.000000,0.069000,0.083300,0.019800,0.000000,0.025000,0.972200,0.000000,0.069000,0.083300,0.019300,0.000000,0.014900,2.0,2.0,-1134.0,1.0,M,N,Y,Working,Secondary / secondary special,Single / not married,Laborers,WEDNESDAY,Business Entity Type 3,"Stone, brick",1.0,0.0,0.0,0.0,Cash loans,0.0,0.0,-606.000000,24.000000,365243.0,-565.000000,125.000000,-25.000000,-17.000000,0.000000,9.000000,1.0,9251.775,179055.00,179055.00,0.00,179055.00,0.000000,NaN,NaN,0.0,1.0,0.0,0.0,0.0,1.0
1,100003.0,0.0,-16765.0,-1188.0,-291.0,1.0,1.0,1.0,11.0,0.0,1.0,270000.0,1293502.5,35698.5,1129500.0,0.003541,-1186.0,2.0,0.311267,0.622246,0.535276,0.095900,0.985100,0.080000,0.034500,0.291700,0.054900,0.009800,0.092400,0.985100,0.080600,0.034500,0.291700,0.055400,0.000000,0.096800,0.985100,0.080000,0.034500,0.291700,0.055800,0.010000,0.071400,1.0,1.0,-828.0,0.0,F,N,N,State servant,Higher education,Married,Core staff,MONDAY,School,Block,0.0,0.0,0.0,0.0,Cash loans,0.0,0.0,-1305.000000,10.000000,365243.0,-1274.333333,-1004.333333,-1054.333333,-1047.333333,0.666667,14.666667,1.0,56553.990,435436.50,484191.00,3442.50,435436.50,0.050030,NaN,NaN,1.0,2.0,0.0,0.0,0.0,3.0
2,100004.0,0.0,-19046.0,-225.0,-2531.0,1.0,2.0,2.0,9.0,0.0,0.0,67500.0,135000.0,6750.0,135000.0,0.010032,-4260.0,1.0,0.272586,0.555912,0.729567,0.025206,0.470849,-0.000261,0.002226,0.026318,0.121398,0.005089,-0.001742,0.217779,0.003516,0.003384,0.142304,0.127024,0.000075,0.000545,0.231712,0.002464,0.031116,0.187131,0.116373,0.000110,0.114492,0.0,0.0,-815.0,0.0,M,Y,Y,Working,Secondary / secondary special,Single / not married,Laborers,MONDAY,Government,Panel,0.0,0.0,0.0,0.0,Revolving loans,0.0,0.0,-815.000000,4.000000,365243.0,-784.000000,-694.000000,-724.000000,-714.000000,0.000000,5.000000,1.0,5357.250,24282.00,20106.00,4860.00,24282.00,0.212008,NaN,NaN,0.0,1.0,0.0,0.0,0.0,1.0
3,100006.0,0.0,-19005.0,-3039.0,-2437.0,0.0,2.0,2.0,17.0,0.0,1.0,135000.0,312682.5,29686.5,297000.0,0.008019,-9833.0,2.0,0.309425,0.650442,0.535276,0.985202,0.494045,0.029242,0.960949,0.040093,0.267515,0.023633,0.156203,0.173594,-0.013866,0.308473,0.169275,0.337387,-0.006964,0.020599,0.254179,0.011039,0.927458,0.226234,0.282553,-0.000445,0.092209,2.0,2.0,-617.0,1.0,F,N,Y,Working,Secondary / secondary special,Civil marriage,Laborers,WEDNESDAY,Business Entity Type 3,Panel,0.0,0.0,0.0,0.0,Cash loans,0.0,0.0,-272.444444,23.000000,365243.0,91066.500000,91584.000000,182477.500000,182481.750000,0.000000,14.666667,1.0,23651.175,272203.26,291695.50,34840.17,408304.89,0.163412,NaN,NaN,5.0,2.0,2.0,0.0,0.0,9.0
4,100007.0,0.0,-19932.0,-3038.0,-3458.0,0.0,2.0,2.0,11.0,1.0,0.0,121500.0,513000.0,21865.5,513000.0,0.028663,-4311.0,1.0,0.272085,0.322738,0.535276,0.025285,0.474059,-0.000519,-0.000514,0.029303,0.130968,0.005942,-0.001721,0.220632,0.003516,0.020376,0.157001,0.117963,0.000075,0.000545,0.239679,0.002464,0.028830,0.185531,0.102443,0.000008,0.155555,0.0,0.0,-1106.0,0.0,M,N,Y,Working,Secondary / secondary special,Single / not married,Core staff,THURSDAY,Religion,Panel,0.0,0.0,0.0,0.0,Cash loans,0.0,0.0,-1222.833333,20.666667,365243.0,-1263.200000,-837.200000,72136.200000,72143.800000,0.600000,12.333333,1.0,12278.805,150530.25,166638.75,3390.75,150530.25,0.159516,NaN,NaN,4.0,2.0,0.0,0.0,0.0,6.0

In [44]:
agg_NAME_CONTRACT_STATUS= previous_app_data.groupby(['SK_ID_CURR', 'NAME_CONTRACT_STATUS']).size().reset_index(name='count')
pivot_of_NAME_CONTRACT_STATUS = agg_NAME_CONTRACT_STATUS.pivot_table(index='SK_ID_CURR', columns='NAME_CONTRACT_STATUS', values='count', fill_value=0)
pivot_of_NAME_CONTRACT_STATUS = pivot_of_NAME_CONTRACT_STATUS.rename(columns={
    "Approved": "Approved_from__contract_from_previous_table",
    "Canceled": "Canceled_loans_from_contract_from_previous_table",
    "Refused": "Refused_from_contract_from_previous_table",
    "Unused offer":"Unused offer_from_contract_from_previous_table"
})
merge_pivot_name_contract_new_app=new_app_data.merge(pivot_of_NAME_CONTRACT_STATUS,how="left",on="SK_ID_CURR")
new_app_data=merge_pivot_name_contract_new_app.copy()
new_app_data.head()

,SK_ID_CURR,CNT_CHILDREN,DAYS_BIRTH,DAYS_EMPLOYED,DAYS_ID_PUBLISH,FLAG_PHONE,REGION_RATING_CLIENT,REGION_RATING_CLIENT_W_CITY,HOUR_APPR_PROCESS_START,REG_CITY_NOT_WORK_CITY,FLAG_DOCUMENT_3,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,REGION_POPULATION_RELATIVE,DAYS_REGISTRATION,CNT_FAM_MEMBERS,EXT_SOURCE_1,EXT_SOURCE_2,EXT_SOURCE_3,APARTMENTS_AVG,YEARS_BEGINEXPLUATATION_AVG,ELEVATORS_AVG,ENTRANCES_AVG,FLOORSMAX_AVG,LIVINGAREA_AVG,NONLIVINGAREA_AVG,APARTMENTS_MODE,YEARS_BEGINEXPLUATATION_MODE,ELEVATORS_MODE,ENTRANCES_MODE,FLOORSMAX_MODE,LIVINGAREA_MODE,NONLIVINGAREA_MODE,APARTMENTS_MEDI,YEARS_BEGINEXPLUATATION_MEDI,ELEVATORS_MEDI,ENTRANCES_MEDI,FLOORSMAX_MEDI,LIVINGAREA_MEDI,NONLIVINGAREA_MEDI,TOTALAREA_MODE,OBS_30_CNT_SOCIAL_CIRCLE,OBS_60_CNT_SOCIAL_CIRCLE,DAYS_LAST_PHONE_CHANGE,AMT_REQ_CREDIT_BUREAU_YEAR,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,OCCUPATION_TYPE,WEEKDAY_APPR_PROCESS_START,ORGANIZATION_TYPE,WALLSMATERIAL_MODE,TARGET,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_MON,NAME_CONTRACT_TYPE,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,DAYS_DECISION_mean_previous_app_data,CNT_PAYMENT_mean_previous_app_data,DAYS_FIRST_DRAWING_mean_previous_app_data,DAYS_FIRST_DUE_mean_previous_app_data,DAYS_LAST_DUE_1ST_VERSION_mean_previous_app_data,DAYS_LAST_DUE_mean_previous_app_data,DAYS_TERMINATION_mean_previous_app_data,NFLAG_INSURED_ON_APPROVAL_mean_previous_app_data,HOUR_APPR_PROCESS_START_mean_previous_app_data,NFLAG_LAST_APPL_IN_DAY_mean_previous_app_data,AMT_ANNUITY_mean_previous_app_data,AMT_APPLICATION_mean_previous_app_data,AMT_CREDIT_mean_previous_app_data,AMT_DOWN_PAYMENT_mean_previous_app_data,AMT_GOODS_PRICE_mean_previous_app_data,RATE_DOWN_PAYMENT_mean_previous_app_data,RATE_INTEREST_PRIMARY_mean_previous_app_data,RATE_INTEREST_PRIVILEGED_mean_previous_app_data,Cash_loans_from__contract_from_previous_table,Consumer_loans_from_contract_from_previous_table,Revolving_loans_from_contract_from_previous_table,XNA_from_contract_from_previous_table,N_loans_from_FLAG_LAST_APPL_PER_CONTRACT_from_previous_table,Y_from__FLAG_LAST_APPL_PER_CONTRACT_from_previous_table,Approved_from__contract_from_previous_table,Canceled_loans_from_contract_from_previous_table,Refused_from_contract_from_previous_table,Unused offer_from_contract_from_previous_table
0,100002.0,0.0,-9461.0,-637.0,-2120.0,1.0,2.0,2.0,10.0,0.0,1.0,202500.0,406597.5,24700.5,351000.0,0.018801,-3648.0,1.0,0.083037,0.262949,0.139376,0.024700,0.972200,0.000000,0.069000,0.083300,0.019000,0.000000,0.025200,0.972200,0.000000,0.069000,0.083300,0.019800,0.000000,0.025000,0.972200,0.000000,0.069000,0.083300,0.019300,0.000000,0.014900,2.0,2.0,-1134.0,1.0,M,N,Y,Working,Secondary / secondary special,Single / not married,Laborers,WEDNESDAY,Business Entity Type 3,"Stone, brick",1.0,0.0,0.0,0.0,Cash loans,0.0,0.0,-606.000000,24.000000,365243.0,-565.000000,125.000000,-25.000000,-17.000000,0.000000,9.000000,1.0,9251.775,179055.00,179055.00,0.00,179055.00,0.000000,NaN,NaN,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0
1,100003.0,0.0,-16765.0,-1188.0,-291.0,1.0,1.0,1.0,11.0,0.0,1.0,270000.0,1293502.5,35698.5,1129500.0,0.003541,-1186.0,2.0,0.311267,0.622246,0.535276,0.095900,0.985100,0.080000,0.034500,0.291700,0.054900,0.009800,0.092400,0.985100,0.080600,0.034500,0.291700,0.055400,0.000000,0.096800,0.985100,0.080000,0.034500,0.291700,0.055800,0.010000,0.071400,1.0,1.0,-828.0,0.0,F,N,N,State servant,Higher education,Married,Core staff,MONDAY,School,Block,0.0,0.0,0.0,0.0,Cash loans,0.0,0.0,-1305.000000,10.000000,365243.0,-1274.333333,-1004.333333,-1054.333333,-1047.333333,0.666667,14.666667,1.0,56553.990,435436.50,484191.00,3442.50,435436.50,0.050030,NaN,NaN,1.0,2.0,0.0,0.0,0.0,3.0,3.0,0.0,0.0,0.0
2,100004.0,0.0,-19046.0,-225.0,-2531.0,1.0,2.0,2.0,9.0,0.0,0.0,67500.0,135000.0,6750.0,135000.0,0.010032,-4260.0,1.0,0.272586,0.555912,0.729567,0.025206,0.470849,-0.000261,0.002226,0.026318,0.121398,0.005089,-0.001742,0.217779,0.003516,0.003384,0.142304,0.127024,0.000075,0.000545,0.231712,0.002464,0.031116,0.187131,0.116373,0.000110,0.114492,0.0,0.0,-815.0,0.0,M,Y,Y,Working,Secondary / secondary special,Single / not married,Laborers,MONDAY,Government,Panel,0.0,0.0,0.0,0.0,Revolving loans,0.0,0.0,-815.000000,4.000000,365243.0,-784.000000,-694.000000,-724.000000,-714.000000,0.000000,5.000000,1.0,5357.250,24282.00,20106.00,4860.00,24282.00,0.212008,NaN,NaN,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0
3,100006.0,0.0,-19005.0,-3039.0,-2437.0,0.0,2.0,2.0,17.0,0.0,1.0,135000.0,312682.5,29686.5,297000.0,0.008019,-9833.0,2.0,0.309425,0.650442,0.535276,0.985202,0.494045,0.029242,0.960949,0.040093,0.267515,0.023633,0.156203,0.173594,-0.013866,0.308473,0.169275,0.337387,-0.006964,0.020599,0.254179,0.011039,0.927458,0.226234,0.282553,-0.000445,0.092209,2.0,2.0,-617.0,1.0,F,N,Y,Working,Secondary / secondary special,Civil marriage,Laborers,WEDNESDAY,Business Entity Type 3,Panel,0.0,0.0,0.0,0.0,Cash loans,0.0,0.0,-272.444444,23.000000,365243.0,91066.500000,91584.000000,182477.500000,182481.750000,0.000000,14.666667,1.0,23651.175,272203.26,291695.50,34840.17,408304.89,0.163412,NaN,NaN,5.0,2.0,2.0,0.0,0.0,9.0,5.0,3.0,1.0,0.0
4,100007.0,0.0,-19932.0,-3038.0,-3458.0,0.0,2.0,2.0,11.0,1.0,0.0,121500.0,513000.0,21865.5,513000.0,0.028663,-4311.0,1.0,0.272085,0.322738,0.535276,0.025285,0.474059,-0.000519,-0.000514,0.029303,0.130968,0.005942,-0.001721,0.220632,0.003516,0.020376,0.157001,0.117963,0.000075,0.000545,0.239679,0.002464,0.028830,0.185531,0.102443,0.000008,0.155555,0.0,0.0,-1106.0,0.0,M,N,Y,Working,Secondary / secondary special,Single / not married,Core staff,THURSDAY,Religion,Panel,0.0,0.0,0.0,0.0,Cash loans,0.0,0.0,-1222.833333,20.666667,365243.0,-1263.200000,-837.200000,72136.200000,72143.800000,0.600000,12.333333,1.0,12278.805,150530.25,166638.75,3390.75,150530.25,0.159516,NaN,NaN,4.0,2.0,0.0,0.0,0.0,6.0,6.0,0.0,0.0,0.0

In [45]:
agg_NAME_PAYMENT_TYPE= previous_app_data.groupby(['SK_ID_CURR', 'NAME_PAYMENT_TYPE']).size().reset_index(name='count')
pivot_of_NAME_PAYMENT_TYPE= agg_NAME_PAYMENT_TYPE.pivot_table(index='SK_ID_CURR', columns='NAME_PAYMENT_TYPE', values='count', fill_value=0)
pivot_of_NAME_PAYMENT_TYPE = pivot_of_NAME_PAYMENT_TYPE.rename(columns={
    "Cash through the bank ": "Cash through the bank _from__name_contract_from_previous_table",
    "XNA": "XNA_from_name_contract_from_previous_table",
    "Non-cash from your account": "Non-cash from your account_from_name_contract_from_previous_table",
    "Cashless from the account of the employer":"Cashless from the account of the employer_name_from_contract_from_previous_table"
})
merge_pivot_NAME_PAYMENT_TYPE=new_app_data.merge(pivot_of_NAME_PAYMENT_TYPE,how="left",on="SK_ID_CURR")
new_app_data=merge_pivot_NAME_PAYMENT_TYPE.copy()
new_app_data.head()

,SK_ID_CURR,CNT_CHILDREN,DAYS_BIRTH,DAYS_EMPLOYED,DAYS_ID_PUBLISH,FLAG_PHONE,REGION_RATING_CLIENT,REGION_RATING_CLIENT_W_CITY,HOUR_APPR_PROCESS_START,REG_CITY_NOT_WORK_CITY,FLAG_DOCUMENT_3,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,REGION_POPULATION_RELATIVE,DAYS_REGISTRATION,CNT_FAM_MEMBERS,EXT_SOURCE_1,EXT_SOURCE_2,EXT_SOURCE_3,APARTMENTS_AVG,YEARS_BEGINEXPLUATATION_AVG,ELEVATORS_AVG,ENTRANCES_AVG,FLOORSMAX_AVG,LIVINGAREA_AVG,NONLIVINGAREA_AVG,APARTMENTS_MODE,YEARS_BEGINEXPLUATATION_MODE,ELEVATORS_MODE,ENTRANCES_MODE,FLOORSMAX_MODE,LIVINGAREA_MODE,NONLIVINGAREA_MODE,APARTMENTS_MEDI,YEARS_BEGINEXPLUATATION_MEDI,ELEVATORS_MEDI,ENTRANCES_MEDI,FLOORSMAX_MEDI,LIVINGAREA_MEDI,NONLIVINGAREA_MEDI,TOTALAREA_MODE,OBS_30_CNT_SOCIAL_CIRCLE,OBS_60_CNT_SOCIAL_CIRCLE,DAYS_LAST_PHONE_CHANGE,AMT_REQ_CREDIT_BUREAU_YEAR,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,OCCUPATION_TYPE,WEEKDAY_APPR_PROCESS_START,ORGANIZATION_TYPE,WALLSMATERIAL_MODE,TARGET,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_MON,NAME_CONTRACT_TYPE,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,DAYS_DECISION_mean_previous_app_data,CNT_PAYMENT_mean_previous_app_data,DAYS_FIRST_DRAWING_mean_previous_app_data,DAYS_FIRST_DUE_mean_previous_app_data,DAYS_LAST_DUE_1ST_VERSION_mean_previous_app_data,DAYS_LAST_DUE_mean_previous_app_data,DAYS_TERMINATION_mean_previous_app_data,NFLAG_INSURED_ON_APPROVAL_mean_previous_app_data,HOUR_APPR_PROCESS_START_mean_previous_app_data,NFLAG_LAST_APPL_IN_DAY_mean_previous_app_data,AMT_ANNUITY_mean_previous_app_data,AMT_APPLICATION_mean_previous_app_data,AMT_CREDIT_mean_previous_app_data,AMT_DOWN_PAYMENT_mean_previous_app_data,AMT_GOODS_PRICE_mean_previous_app_data,RATE_DOWN_PAYMENT_mean_previous_app_data,RATE_INTEREST_PRIMARY_mean_previous_app_data,RATE_INTEREST_PRIVILEGED_mean_previous_app_data,Cash_loans_from__contract_from_previous_table,Consumer_loans_from_contract_from_previous_table,Revolving_loans_from_contract_from_previous_table,XNA_from_contract_from_previous_table,N_loans_from_FLAG_LAST_APPL_PER_CONTRACT_from_previous_table,Y_from__FLAG_LAST_APPL_PER_CONTRACT_from_previous_table,Approved_from__contract_from_previous_table,Canceled_loans_from_contract_from_previous_table,Refused_from_contract_from_previous_table,Unused offer_from_contract_from_previous_table,Cash through the bank,Cashless from the account of the employer_name_from_contract_from_previous_table,Non-cash from your account_from_name_contract_from_previous_table,XNA_from_name_contract_from_previous_table
0,100002.0,0.0,-9461.0,-637.0,-2120.0,1.0,2.0,2.0,10.0,0.0,1.0,202500.0,406597.5,24700.5,351000.0,0.018801,-3648.0,1.0,0.083037,0.262949,0.139376,0.024700,0.972200,0.000000,0.069000,0.083300,0.019000,0.000000,0.025200,0.972200,0.000000,0.069000,0.083300,0.019800,0.000000,0.025000,0.972200,0.000000,0.069000,0.083300,0.019300,0.000000,0.014900,2.0,2.0,-1134.0,1.0,M,N,Y,Working,Secondary / secondary special,Single / not married,Laborers,WEDNESDAY,Business Entity Type 3,"Stone, brick",1.0,0.0,0.0,0.0,Cash loans,0.0,0.0,-606.000000,24.000000,365243.0,-565.000000,125.000000,-25.000000,-17.000000,0.000000,9.000000,1.0,9251.775,179055.00,179055.00,0.00,179055.00,0.000000,NaN,NaN,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,100003.0,0.0,-16765.0,-1188.0,-291.0,1.0,1.0,1.0,11.0,0.0,1.0,270000.0,1293502.5,35698.5,1129500.0,0.003541,-1186.0,2.0,0.311267,0.622246,0.535276,0.095900,0.985100,0.080000,0.034500,0.291700,0.054900,0.009800,0.092400,0.985100,0.080600,0.034500,0.291700,0.055400,0.000000,0.096800,0.985100,0.080000,0.034500,0.291700,0.055800,0.010000,0.071400,1.0,1.0,-828.0,0.0,F,N,N,State servant,Higher education,Married,Core staff,MONDAY,School,Block,0.0,0.0,0.0,0.0,Cash loans,0.0,0.0,-1305.000000,10.000000,365243.0,-1274.333333,-1004.333333,-1054.333333,-1047.333333,0.666667,14.666667,1.0,56553.990,435436.50,484191.00,3442.50,435436.50,0.050030,NaN,NaN,1.0,2.0,0.0,0.0,0.0,3.0,3.0,0.0,0.0,0.0,2.0,0.0,0.0,1.0
2,100004.0,0.0,-19046.0,-225.0,-2531.0,1.0,2.0,2.0,9.0,0.0,0.0,67500.0,135000.0,6750.0,135000.0,0.010032,-4260.0,1.0,0.272586,0.555912,0.729567,0.025206,0.470849,-0.000261,0.002226,0.026318,0.121398,0.005089,-0.001742,0.217779,0.003516,0.003384,0.142304,0.127024,0.000075,0.000545,0.231712,0.002464,0.031116,0.187131,0.116373,0.000110,0.114492,0.0,0.0,-815.0,0.0,M,Y,Y,Working,Secondary / secondary special,Single / not married,Laborers,MONDAY,Government,Panel,0.0,0.0,0.0,0.0,Revolving loans,0.0,0.0,-815.000000,4.000000,365243.0,-784.000000,-694.000000,-724.000000,-714.000000,0.000000,5.000000,1.0,5357.250,24282.00,20106.00,4860.00,24282.00,0.212008,NaN,NaN,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
3,100006.0,0.0,-19005.0,-3039.0,-2437.0,0.0,2.0,2.0,17.0,0.0,1.0,135000.0,312682.5,29686.5,297000.0,0.008019,-9833.0,2.0,0.309425,0.650442,0.535276,0.985202,0.494045,0.029242,0.960949,0.040093,0.267515,0.023633,0.156203,0.173594,-0.013866,0.308473,0.169275,0.337387,-0.006964,0.020599,0.254179,0.011039,0.927458,0.226234,0.282553,-0.000445,0.092209,2.0,2.0,-617.0,1.0,F,N,Y,Working,Secondary / secondary special,Civil marriage,Laborers,WEDNESDAY,Business Entity Type 3,Panel,0.0,0.0,0.0,0.0,Cash loans,0.0,0.0,-272.444444,23.000000,365243.0,91066.500000,91584.000000,182477.500000,182481.750000,0.000000,14.666667,1.0,23651.175,272203.26,291695.50,34840.17,408304.89,0.163412,NaN,NaN,5.0,2.0,2.0,0.0,0.0,9.0,5.0,3.0,1.0,0.0,4.0,0.0,0.0,5.0
4,100007.0,0.0,-19932.0,-3038.0,-3458.0,0.0,2.0,2.0,11.0,1.0,0.0,121500.0,513000.0,21865.5,513000.0,0.028663,-4311.0,1.0,0.272085,0.322738,0.535276,0.025285,0.474059,-0.000519,-0.000514,0.029303,0.130968,0.005942,-0.001721,0.220632,0.003516,0.020376,0.157001,0.117963,0.000075,0.000545,0.239679,0.002464,0.028830,0.185531,0.102443,0.000008,0.155555,0.0,0.0,-1106.0,0.0,M,N,Y,Working,Secondary / secondary special,Single / not married,Core staff,THURSDAY,Religion,Panel,0.0,0.0,0.0,0.0,Cash loans,0.0,0.0,-1222.833333,20.666667,365243.0,-1263.200000,-837.200000,72136.200000,72143.800000,0.600000,12.333333,1.0,12278.805,150530.25,166638.75,3390.75,150530.25,0.159516,NaN,NaN,4.0,2.0,0.0,0.0,0.0,6.0,6.0,0.0,0.0,0.0,5.0,0.0,0.0,1.0

In [46]:
agg_NAME_PRODUCT_TYPE= previous_app_data.groupby(['SK_ID_CURR', 'NAME_PRODUCT_TYPE']).size().reset_index(name='count')
pivot_of_NAME_PRODUCT_TYPE= agg_NAME_PRODUCT_TYPE.pivot_table(index='SK_ID_CURR', columns='NAME_PRODUCT_TYPE', values='count', fill_value=0)
pivot_of_NAME_PRODUCT_TYPE = pivot_of_NAME_PRODUCT_TYPE.rename(columns={
    "XNA": "XNA_from__NAME_PRODUCT_TYPE_from_previous_table",
    "x-sell": "x-sell_from_NAME_PRODUCT_TYPE_from_previous_table",
    "walk-in": "walk_in_from_NAME_PRODUCT_TYPE_from_previous_table",
})
merge_pivot_NAME_PRODUCT_TYPE=new_app_data.merge(pivot_of_NAME_PRODUCT_TYPE,how="left",on="SK_ID_CURR")
new_app_data=merge_pivot_NAME_PRODUCT_TYPE.copy()
new_app_data.head()

,SK_ID_CURR,CNT_CHILDREN,DAYS_BIRTH,DAYS_EMPLOYED,DAYS_ID_PUBLISH,FLAG_PHONE,REGION_RATING_CLIENT,REGION_RATING_CLIENT_W_CITY,HOUR_APPR_PROCESS_START,REG_CITY_NOT_WORK_CITY,FLAG_DOCUMENT_3,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,REGION_POPULATION_RELATIVE,DAYS_REGISTRATION,CNT_FAM_MEMBERS,EXT_SOURCE_1,EXT_SOURCE_2,EXT_SOURCE_3,APARTMENTS_AVG,YEARS_BEGINEXPLUATATION_AVG,ELEVATORS_AVG,ENTRANCES_AVG,FLOORSMAX_AVG,LIVINGAREA_AVG,NONLIVINGAREA_AVG,APARTMENTS_MODE,YEARS_BEGINEXPLUATATION_MODE,ELEVATORS_MODE,ENTRANCES_MODE,FLOORSMAX_MODE,LIVINGAREA_MODE,NONLIVINGAREA_MODE,APARTMENTS_MEDI,YEARS_BEGINEXPLUATATION_MEDI,ELEVATORS_MEDI,ENTRANCES_MEDI,FLOORSMAX_MEDI,LIVINGAREA_MEDI,NONLIVINGAREA_MEDI,TOTALAREA_MODE,OBS_30_CNT_SOCIAL_CIRCLE,OBS_60_CNT_SOCIAL_CIRCLE,DAYS_LAST_PHONE_CHANGE,AMT_REQ_CREDIT_BUREAU_YEAR,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,OCCUPATION_TYPE,WEEKDAY_APPR_PROCESS_START,ORGANIZATION_TYPE,WALLSMATERIAL_MODE,TARGET,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_MON,NAME_CONTRACT_TYPE,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,DAYS_DECISION_mean_previous_app_data,CNT_PAYMENT_mean_previous_app_data,DAYS_FIRST_DRAWING_mean_previous_app_data,DAYS_FIRST_DUE_mean_previous_app_data,DAYS_LAST_DUE_1ST_VERSION_mean_previous_app_data,DAYS_LAST_DUE_mean_previous_app_data,DAYS_TERMINATION_mean_previous_app_data,NFLAG_INSURED_ON_APPROVAL_mean_previous_app_data,HOUR_APPR_PROCESS_START_mean_previous_app_data,NFLAG_LAST_APPL_IN_DAY_mean_previous_app_data,AMT_ANNUITY_mean_previous_app_data,AMT_APPLICATION_mean_previous_app_data,AMT_CREDIT_mean_previous_app_data,AMT_DOWN_PAYMENT_mean_previous_app_data,AMT_GOODS_PRICE_mean_previous_app_data,RATE_DOWN_PAYMENT_mean_previous_app_data,RATE_INTEREST_PRIMARY_mean_previous_app_data,RATE_INTEREST_PRIVILEGED_mean_previous_app_data,Cash_loans_from__contract_from_previous_table,Consumer_loans_from_contract_from_previous_table,Revolving_loans_from_contract_from_previous_table,XNA_from_contract_from_previous_table,N_loans_from_FLAG_LAST_APPL_PER_CONTRACT_from_previous_table,Y_from__FLAG_LAST_APPL_PER_CONTRACT_from_previous_table,Approved_from__contract_from_previous_table,Canceled_loans_from_contract_from_previous_table,Refused_from_contract_from_previous_table,Unused offer_from_contract_from_previous_table,Cash through the bank,Cashless from the account of the employer_name_from_contract_from_previous_table,Non-cash from your account_from_name_contract_from_previous_table,XNA_from_name_contract_from_previous_table,XNA_from__NAME_PRODUCT_TYPE_from_previous_table,walk_in_from_NAME_PRODUCT_TYPE_from_previous_table,x-sell_from_NAME_PRODUCT_TYPE_from_previous_table
0,100002.0,0.0,-9461.0,-637.0,-2120.0,1.0,2.0,2.0,10.0,0.0,1.0,202500.0,406597.5,24700.5,351000.0,0.018801,-3648.0,1.0,0.083037,0.262949,0.139376,0.024700,0.972200,0.000000,0.069000,0.083300,0.019000,0.000000,0.025200,0.972200,0.000000,0.069000,0.083300,0.019800,0.000000,0.025000,0.972200,0.000000,0.069000,0.083300,0.019300,0.000000,0.014900,2.0,2.0,-1134.0,1.0,M,N,Y,Working,Secondary / secondary special,Single / not married,Laborers,WEDNESDAY,Business Entity Type 3,"Stone, brick",1.0,0.0,0.0,0.0,Cash loans,0.0,0.0,-606.000000,24.000000,365243.0,-565.000000,125.000000,-25.000000,-17.000000,0.000000,9.000000,1.0,9251.775,179055.00,179055.00,0.00,179055.00,0.000000,NaN,NaN,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0
1,100003.0,0.0,-16765.0,-1188.0,-291.0,1.0,1.0,1.0,11.0,0.0,1.0,270000.0,1293502.5,35698.5,1129500.0,0.003541,-1186.0,2.0,0.311267,0.622246,0.535276,0.095900,0.985100,0.080000,0.034500,0.291700,0.054900,0.009800,0.092400,0.985100,0.080600,0.034500,0.291700,0.055400,0.000000,0.096800,0.985100,0.080000,0.034500,0.291700,0.055800,0.010000,0.071400,1.0,1.0,-828.0,0.0,F,N,N,State servant,Higher education,Married,Core staff,MONDAY,School,Block,0.0,0.0,0.0,0.0,Cash loans,0.0,0.0,-1305.000000,10.000000,365243.0,-1274.333333,-1004.333333,-1054.333333,-1047.333333,0.666667,14.666667,1.0,56553.990,435436.50,484191.00,3442.50,435436.50,0.050030,NaN,NaN,1.0,2.0,0.0,0.0,0.0,3.0,3.0,0.0,0.0,0.0,2.0,0.0,0.0,1.0,2.0,0.0,1.0
2,100004.0,0.0,-19046.0,-225.0,-2531.0,1.0,2.0,2.0,9.0,0.0,0.0,67500.0,135000.0,6750.0,135000.0,0.010032,-4260.0,1.0,0.272586,0.555912,0.729567,0.025206,0.470849,-0.000261,0.002226,0.026318,0.121398,0.005089,-0.001742,0.217779,0.003516,0.003384,0.142304,0.127024,0.000075,0.000545,0.231712,0.002464,0.031116,0.187131,0.116373,0.000110,0.114492,0.0,0.0,-815.0,0.0,M,Y,Y,Working,Secondary / secondary special,Single / not married,Laborers,MONDAY,Government,Panel,0.0,0.0,0.0,0.0,Revolving loans,0.0,0.0,-815.000000,4.000000,365243.0,-784.000000,-694.000000,-724.000000,-714.000000,0.000000,5.000000,1.0,5357.250,24282.00,20106.00,4860.00,24282.00,0.212008,NaN,NaN,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
3,100006.0,0.0,-19005.0,-3039.0,-2437.0,0.0,2.0,2.0,17.0,0.0,1.0,135000.0,312682.5,29686.5,297000.0,0.008019,-9833.0,2.0,0.309425,0.650442,0.535276,0.985202,0.494045,0.029242,0.960949,0.040093,0.267515,0.023633,0.156203,0.173594,-0.013866,0.308473,0.169275,0.337387,-0.006964,0.020599,0.254179,0.011039,0.927458,0.226234,0.282553,-0.000445,0.092209,2.0,2.0,-617.0,1.0,F,N,Y,Working,Secondary / secondary special,Civil marriage,Laborers,WEDNESDAY,Business Entity Type 3,Panel,0.0,0.0,0.0,0.0,Cash loans,0.0,0.0,-272.444444,23.000000,365243.0,91066.500000,91584.000000,182477.500000,182481.750000,0.000000,14.666667,1.0,23651.175,272203.26,291695.50,34840.17,408304.89,0.163412,NaN,NaN,5.0,2.0,2.0,0.0,0.0,9.0,5.0,3.0,1.0,0.0,4.0,0.0,0.0,5.0,5.0,0.0,4.0
4,100007.0,0.0,-19932.0,-3038.0,-3458.0,0.0,2.0,2.0,11.0,1.0,0.0,121500.0,513000.0,21865.5,513000.0,0.028663,-4311.0,1.0,0.272085,0.322738,0.535276,0.025285,0.474059,-0.000519,-0.000514,0.029303,0.130968,0.005942,-0.001721,0.220632,0.003516,0.020376,0.157001,0.117963,0.000075,0.000545,0.239679,0.002464,0.028830,0.185531,0.102443,0.000008,0.155555,0.0,0.0,-1106.0,0.0,M,N,Y,Working,Secondary / secondary special,Single / not married,Core staff,THURSDAY,Religion,Panel,0.0,0.0,0.0,0.0,Cash loans,0.0,0.0,-1222.833333,20.666667,365243.0,-1263.200000,-837.200000,72136.200000,72143.800000,0.600000,12.333333,1.0,12278.805,150530.25,166638.75,3390.75,150530.25,0.159516,NaN,NaN,4.0,2.0,0.0,0.0,0.0,6.0,6.0,0.0,0.0,0.0,5.0,0.0,0.0,1.0,2.0,1.0,3.0

In [47]:
agg_NAME_YIELD_GROUP= previous_app_data.groupby(['SK_ID_CURR', 'NAME_YIELD_GROUP']).size().reset_index(name='count')
pivot_of_NAME_YIELD_GROUP= agg_NAME_YIELD_GROUP.pivot_table(index='SK_ID_CURR', columns='NAME_YIELD_GROUP', values='count', fill_value=0)
pivot_of_NAME_YIELD_GROUP = pivot_of_NAME_YIELD_GROUP.rename(columns={
    "XNA": "XNA_from__NAME_YIELD_GROUP_from_previous_table",
    "middle": "middle_from_NAME_YIELD_GROUP_from_previous_table",
    "high": "high_from_NAME_YIELD_GROUP_from_previous_table",
    "low_normal":"low_normal_from_NAME_YIELD_GROUP_from_previous_table",
    "low_action":"low_action_from_NAME_YIELD_GROUP_from_previous_table"
})
merge_pivot_NAME_YIELD_GROUP=new_app_data.merge(pivot_of_NAME_YIELD_GROUP,how="left",on="SK_ID_CURR")
new_app_data=merge_pivot_NAME_YIELD_GROUP.copy()
new_app_data.head()

,SK_ID_CURR,CNT_CHILDREN,DAYS_BIRTH,DAYS_EMPLOYED,DAYS_ID_PUBLISH,FLAG_PHONE,REGION_RATING_CLIENT,REGION_RATING_CLIENT_W_CITY,HOUR_APPR_PROCESS_START,REG_CITY_NOT_WORK_CITY,FLAG_DOCUMENT_3,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,REGION_POPULATION_RELATIVE,DAYS_REGISTRATION,CNT_FAM_MEMBERS,EXT_SOURCE_1,EXT_SOURCE_2,EXT_SOURCE_3,APARTMENTS_AVG,YEARS_BEGINEXPLUATATION_AVG,ELEVATORS_AVG,ENTRANCES_AVG,FLOORSMAX_AVG,LIVINGAREA_AVG,NONLIVINGAREA_AVG,APARTMENTS_MODE,YEARS_BEGINEXPLUATATION_MODE,ELEVATORS_MODE,ENTRANCES_MODE,FLOORSMAX_MODE,LIVINGAREA_MODE,NONLIVINGAREA_MODE,APARTMENTS_MEDI,YEARS_BEGINEXPLUATATION_MEDI,ELEVATORS_MEDI,ENTRANCES_MEDI,FLOORSMAX_MEDI,LIVINGAREA_MEDI,NONLIVINGAREA_MEDI,TOTALAREA_MODE,OBS_30_CNT_SOCIAL_CIRCLE,OBS_60_CNT_SOCIAL_CIRCLE,DAYS_LAST_PHONE_CHANGE,AMT_REQ_CREDIT_BUREAU_YEAR,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,OCCUPATION_TYPE,WEEKDAY_APPR_PROCESS_START,ORGANIZATION_TYPE,WALLSMATERIAL_MODE,TARGET,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_MON,NAME_CONTRACT_TYPE,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,DAYS_DECISION_mean_previous_app_data,CNT_PAYMENT_mean_previous_app_data,DAYS_FIRST_DRAWING_mean_previous_app_data,DAYS_FIRST_DUE_mean_previous_app_data,DAYS_LAST_DUE_1ST_VERSION_mean_previous_app_data,DAYS_LAST_DUE_mean_previous_app_data,DAYS_TERMINATION_mean_previous_app_data,NFLAG_INSURED_ON_APPROVAL_mean_previous_app_data,HOUR_APPR_PROCESS_START_mean_previous_app_data,NFLAG_LAST_APPL_IN_DAY_mean_previous_app_data,AMT_ANNUITY_mean_previous_app_data,AMT_APPLICATION_mean_previous_app_data,AMT_CREDIT_mean_previous_app_data,AMT_DOWN_PAYMENT_mean_previous_app_data,AMT_GOODS_PRICE_mean_previous_app_data,RATE_DOWN_PAYMENT_mean_previous_app_data,RATE_INTEREST_PRIMARY_mean_previous_app_data,RATE_INTEREST_PRIVILEGED_mean_previous_app_data,Cash_loans_from__contract_from_previous_table,Consumer_loans_from_contract_from_previous_table,Revolving_loans_from_contract_from_previous_table,XNA_from_contract_from_previous_table,N_loans_from_FLAG_LAST_APPL_PER_CONTRACT_from_previous_table,Y_from__FLAG_LAST_APPL_PER_CONTRACT_from_previous_table,Approved_from__contract_from_previous_table,Canceled_loans_from_contract_from_previous_table,Refused_from_contract_from_previous_table,Unused offer_from_contract_from_previous_table,Cash through the bank,Cashless from the account of the employer_name_from_contract_from_previous_table,Non-cash from your account_from_name_contract_from_previous_table,XNA_from_name_contract_from_previous_table,XNA_from__NAME_PRODUCT_TYPE_from_previous_table,walk_in_from_NAME_PRODUCT_TYPE_from_previous_table,x-sell_from_NAME_PRODUCT_TYPE_from_previous_table,XNA_from__NAME_YIELD_GROUP_from_previous_table,high_from_NAME_YIELD_GROUP_from_previous_table,low_action_from_NAME_YIELD_GROUP_from_previous_table,low_normal_from_NAME_YIELD_GROUP_from_previous_table,middle_from_NAME_YIELD_GROUP_from_previous_table
0,100002.0,0.0,-9461.0,-637.0,-2120.0,1.0,2.0,2.0,10.0,0.0,1.0,202500.0,406597.5,24700.5,351000.0,0.018801,-3648.0,1.0,0.083037,0.262949,0.139376,0.024700,0.972200,0.000000,0.069000,0.083300,0.019000,0.000000,0.025200,0.972200,0.000000,0.069000,0.083300,0.019800,0.000000,0.025000,0.972200,0.000000,0.069000,0.083300,0.019300,0.000000,0.014900,2.0,2.0,-1134.0,1.0,M,N,Y,Working,Secondary / secondary special,Single / not married,Laborers,WEDNESDAY,Business Entity Type 3,"Stone, brick",1.0,0.0,0.0,0.0,Cash loans,0.0,0.0,-606.000000,24.000000,365243.0,-565.000000,125.000000,-25.000000,-17.000000,0.000000,9.000000,1.0,9251.775,179055.00,179055.00,0.00,179055.00,0.000000,NaN,NaN,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,100003.0,0.0,-16765.0,-1188.0,-291.0,1.0,1.0,1.0,11.0,0.0,1.0,270000.0,1293502.5,35698.5,1129500.0,0.003541,-1186.0,2.0,0.311267,0.622246,0.535276,0.095900,0.985100,0.080000,0.034500,0.291700,0.054900,0.009800,0.092400,0.985100,0.080600,0.034500,0.291700,0.055400,0.000000,0.096800,0.985100,0.080000,0.034500,0.291700,0.055800,0.010000,0.071400,1.0,1.0,-828.0,0.0,F,N,N,State servant,Higher education,Married,Core staff,MONDAY,School,Block,0.0,0.0,0.0,0.0,Cash loans,0.0,0.0,-1305.000000,10.000000,365243.0,-1274.333333,-1004.333333,-1054.333333,-1047.333333,0.666667,14.666667,1.0,56553.990,435436.50,484191.00,3442.50,435436.50,0.050030,NaN,NaN,1.0,2.0,0.0,0.0,0.0,3.0,3.0,0.0,0.0,0.0,2.0,0.0,0.0,1.0,2.0,0.0,1.0,0.0,0.0,0.0,1.0,2.0
2,100004.0,0.0,-19046.0,-225.0,-2531.0,1.0,2.0,2.0,9.0,0.0,0.0,67500.0,135000.0,6750.0,135000.0,0.010032,-4260.0,1.0,0.272586,0.555912,0.729567,0.025206,0.470849,-0.000261,0.002226,0.026318,0.121398,0.005089,-0.001742,0.217779,0.003516,0.003384,0.142304,0.127024,0.000075,0.000545,0.231712,0.002464,0.031116,0.187131,0.116373,0.000110,0.114492,0.0,0.0,-815.0,0.0,M,Y,Y,Working,Secondary / secondary special,Single / not married,Laborers,MONDAY,Government,Panel,0.0,0.0,0.0,0.0,Revolving loans,0.0,0.0,-815.000000,4.000000,365243.0,-784.000000,-694.000000,-724.000000,-714.000000,0.000000,5.000000,1.0,5357.250,24282.00,20106.00,4860.00,24282.00,0.212008,NaN,NaN,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,100006.0,0.0,-19005.0,-3039.0,-2437.0,0.0,2.0,2.0,17.0,0.0,1.0,135000.0,312682.5,29686.5,297000.0,0.008019,-9833.0,2.0,0.309425,0.650442,0.535276,0.985202,0.494045,0.029242,0.960949,0.040093,0.267515,0.023633,0.156203,0.173594,-0.013866,0.308473,0.169275,0.337387,-0.006964,0.020599,0.254179,0.011039,0.927458,0.226234,0.282553,-0.000445,0.092209,2.0,2.0,-617.0,1.0,F,N,Y,Working,Secondary / secondary special,Civil marriage,Laborers,WEDNESDAY,Business Entity Type 3,Panel,0.0,0.0,0.0,0.0,Cash loans,0.0,0.0,-272.444444,23.000000,365243.0,91066.500000,91584.000000,182477.500000,182481.750000,0.000000,14.666667,1.0,23651.175,272203.26,291695.50,34840.17,408304.89,0.163412,NaN,NaN,5.0,2.0,2.0,0.0,0.0,9.0,5.0,3.0,1.0,0.0,4.0,0.0,0.0,5.0,5.0,0.0,4.0,4.0,2.0,0.0,2.0,1.0
4,100007.0,0.0,-19932.0,-3038.0,-3458.0,0.0,2.0,2.0,11.0,1.0,0.0,121500.0,513000.0,21865.5,513000.0,0.028663,-4311.0,1.0,0.272085,0.322738,0.535276,0.025285,0.474059,-0.000519,-0.000514,0.029303,0.130968,0.005942,-0.001721,0.220632,0.003516,0.020376,0.157001,0.117963,0.000075,0.000545,0.239679,0.002464,0.028830,0.185531,0.102443,0.000008,0.155555,0.0,0.0,-1106.0,0.0,M,N,Y,Working,Secondary / secondary special,Single / not married,Core staff,THURSDAY,Religion,Panel,0.0,0.0,0.0,0.0,Cash loans,0.0,0.0,-1222.833333,20.666667,365243.0,-1263.200000,-837.200000,72136.200000,72143.800000,0.600000,12.333333,1.0,12278.805,150530.25,166638.75,3390.75,150530.25,0.159516,NaN,NaN,4.0,2.0,0.0,0.0,0.0,6.0,6.0,0.0,0.0,0.0,5.0,0.0,0.0,1.0,2.0,1.0,3.0,0.0,3.0,0.0,0.0,3.0

In [49]:
new_app_data.columns

Index(['SK_ID_CURR', 'CNT_CHILDREN', 'DAYS_BIRTH', 'DAYS_EMPLOYED',
       'DAYS_ID_PUBLISH', 'FLAG_PHONE', 'REGION_RATING_CLIENT',
       'REGION_RATING_CLIENT_W_CITY', 'HOUR_APPR_PROCESS_START',
       'REG_CITY_NOT_WORK_CITY',
       ...
       'Non-cash from your account_from_name_contract_from_previous_table',
       'XNA_from_name_contract_from_previous_table',
       'XNA_from__NAME_PRODUCT_TYPE_from_previous_table',
       'walk_in_from_NAME_PRODUCT_TYPE_from_previous_table',
       'x-sell_from_NAME_PRODUCT_TYPE_from_previous_table',
       'XNA_from__NAME_YIELD_GROUP_from_previous_table',
       'high_from_NAME_YIELD_GROUP_from_previous_table',
       'low_action_from_NAME_YIELD_GROUP_from_previous_table',
       'low_normal_from_NAME_YIELD_GROUP_from_previous_table',
       'middle_from_NAME_YIELD_GROUP_from_previous_table'],
      dtype='object', length=104)

# feature engineering and replcae outlieres with null values

In [66]:
#da4=new_app_data[['DAYS_ID_PUBLISH']].copy()
new_app_data['DAYS_ID_PUBLISH_Years']=new_app_data['DAYS_ID_PUBLISH']/365
new_app_data['DAYS_ID_PUBLISH_Years'].min()

-19.71780821917808

In [68]:
#da = new_app_data[['DAYS_BIRTH']].copy()
new_app_data['DAYS_BIRTH_YEARS'] = new_app_data['DAYS_BIRTH'] / 365
new_app_data['DAYS_BIRTH_YEARS'].min()

-69.12054794520547

In [69]:

columns = ["DAYS_BIRTH_YEARS", "DAYS_REGISTRATION_Year", "DAYS_ID_PUBLISH_Years", "DAYS_EMPLOYED_Years"]

# Function to calculate IQR and replace outliers with NaN
def replace_outliers_with_nan(df, col):
    q1 = np.percentile(df[col], 25, interpolation="midpoint")
    q3 = np.percentile(df[col], 75, interpolation="midpoint")
    iqr = q3 - q1
    lower_bound = q1 - 1.5 * iqr
    upper_bound = q3 + 1.5 * iqr
    df[col] = df[col].apply(lambda x: np.nan if x < lower_bound or x > upper_bound else x)

for col in columns:
    replace_outliers_with_nan(new_app_data, col)

C:\Users\youss\AppData\Local\Temp\ipykernel_25244\1614184561.py:13: DeprecationWarning: the `interpolation=` argument to percentile was renamed to `method=`, which has additional options.
Users of the modes 'nearest', 'lower', 'higher', or 'midpoint' are encouraged to review the method they used. (Deprecated NumPy 1.22)
  replace_outliers_with_nan(new_app_data, col)

In [70]:
new_app_data[columns].isnull().sum()

DAYS_BIRTH_YEARS              0
DAYS_REGISTRATION_Year      659
DAYS_ID_PUBLISH_Years         0
DAYS_EMPLOYED_Years       72217
dtype: int64

In [72]:
columns = ["DAYS_BIRTH", "DAYS_REGISTRATION", "DAYS_ID_PUBLISH", "DAYS_EMPLOYED"]

new_app_data.drop(columns, axis=1, inplace=True)

In [73]:
new_app_data.columns

Index(['SK_ID_CURR', 'CNT_CHILDREN', 'FLAG_PHONE', 'REGION_RATING_CLIENT',
       'REGION_RATING_CLIENT_W_CITY', 'HOUR_APPR_PROCESS_START',
       'REG_CITY_NOT_WORK_CITY', 'FLAG_DOCUMENT_3', 'AMT_INCOME_TOTAL',
       'AMT_CREDIT',
       ...
       'x-sell_from_NAME_PRODUCT_TYPE_from_previous_table',
       'XNA_from__NAME_YIELD_GROUP_from_previous_table',
       'high_from_NAME_YIELD_GROUP_from_previous_table',
       'low_action_from_NAME_YIELD_GROUP_from_previous_table',
       'low_normal_from_NAME_YIELD_GROUP_from_previous_table',
       'middle_from_NAME_YIELD_GROUP_from_previous_table',
       'DAYS_EMPLOYED_Years', 'DAYS_REGISTRATION_Year',
       'DAYS_ID_PUBLISH_Years', 'DAYS_BIRTH_YEARS'],
      dtype='object', length=104)